src/ASM/ASMs2D.C
src/ASM/ASMs3D.C
src/ASM/IntegrandBase.h
src/ASM/NewmarkMats.C
src/ASM/NewmarkMats.h
src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h
src/SIM/GenAlphaSIM.C
src/SIM/NewmarkSIM.C
src/SIM/NewmarkSIM.h
src/SIM/Property.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/Test/TestInitialConditions.C
src/SIM/Test/TestNewmark.C
src/Utility/Test/TestUtilities.C
src/Utility/Test/refdata/getattribute.xml
src/Utility/Utilities.C
src/Utility/Utilities.h

This replaces #13. Contains some extension to utl::matrix and other smaller things.
Required by the coupled poroelastic fracture solver.

Matrix extension

---

src/IFEM.C
src/IFEM.h.in

Such that it does not need to repeated in all the main programs,
and also to reflect the correct command for parallel runs.
Bare et forslag, må testes i parallel setting også.

Added: Outprint of simulator title and the executing command.

---

Apps/Common/Test/TestStabilizationUtils.C
src/Utility/CoordinateMapping.C

Afaik the G-matrix definition uses a (-1,1)^d reference element, but this is mostly CFD-motivated, and this is the only place where the G-matrix is used in IFEM.

fix: follow standard definition of G-matrix.

---

src/LinAlg/DenseMatrix.C
src/LinAlg/DenseMatrix.h

allows easy access to the solve method, which will be require in NavierStokes for div-compatible VMS

add utl::Matrix constructor to DenseMatrix

---

Apps/Common/Test/TestMeshUtils.C
src/SIM/SIM1D.C
src/SIM/SIM2D.C
src/SIM/SIM3D.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMgeneric.C

Translates to local patch index and ignores patch entries on other processes.
The nGlPatches member of SIMbase is now default equal to myModel.size() for
serial runs, such that we don't need to check that it is non-zero all the time
(except for in getLocalPatchIndex, which may be called before it is set).
The latter is now treated as an error conditions and indicates missing
partitioning information for parallel runs.
Alternative to #42, checking.

Fixed: Allow using the <refine> and <raiseorder> keywords in parallel

---

src/SIM/EigenModeSIM.C
src/SIM/NewmarkSIM.C
src/SIM/NonLinSIM.C
src/SIM/NonLinSIM.h

Two things here:
1. Use the adm.cout for iteration output for all MultiStepSIM drivers (for consistency).
2. Fixed NonLinSIMM::lineSearch method. Now this method works as anticipated.

Line search fix and output to correct cout

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h

Some fixes for the mixed LR ASM module. I can now run 'mixed' Stokes fine through LR. More stuff will be amended to fix compatible stokes + LR, so hold on the merge (but feel free to review now)!
@kmokstad please have a look at the printing commit.

Fix mixed LR

---

src/ASM/ASMbase.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h
src/ASM/ASMstruct.C
src/ASM/ASMstruct.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h

apps can be structured so that this is okay. this is done in the CFD
applications that is the main consumer of this functionality.
this suppresses scary (but actually harmless) warnings

changed: introduce a flag to ignore global multipliers in multithreading sanity check

---

src/SIM/SIM1D.C
src/SIM/SIM2D.C
src/SIM/SIM3D.C
src/SIM/SIMinput.C
src/SIM/SIMinput.h

Used by the <refine> and <raisorder> tags. It also allows specifying a topology set defining the patch(es) to refine.
This is a redo of #71 but (in my opinion) in a more elegant way.
The functionality should be exactly the same.

Added: protected method SIMinput::parseTopologySet

---

Apps/Common/SIMCoupled.h
Apps/Common/SIMCoupledSI.h
src/ASM/ASMs1D.C
src/SIM/MultiStepSIM.h
src/Utility/Tensor.C
src/Utility/Tensor.h

telling which one of the two sub-step solvers to invoke first.
Not sure if there is a better way of doing this. But the clue is that I want the option to solve S2 before S1 without swapping the template argument (because VTF export, etc. is connected to S1).

Added: Optional second argument to the solveStep method

---

src/SIM/SIM2D.C
src/SIM/SIM3D.C

need to use number of global patches, check local patch index
like everything else.

fixed: allow usage of <periodic> in parallel

---

Apps/Common/SIMSemi3D.h
src/ASM/ASMs2D.h
src/ASM/ASMs2DmxLag.C
src/ASM/ASMs2DmxLag.h
src/ASM/ASMs3DmxLag.C
src/ASM/ASMs3DmxLag.h
src/ASM/SAMpatchPETSc.h
src/LinAlg/PETScMatrix.C
src/SIM/Test/TestModelGenerator.C

With these fixes, clang now compiles IFEM-core and CFD applications warnings-less except a few issues which are taken care of in https://github.com/OPM/IFEM/pull/102
Replaces #117

Quell warnings with clang

---

src/SIM/SIMinput.C

Latest in the silly hacks series. Without this it's impossible to get scalar Neumann conditions on sims with more than one field. Useful e.g. in poroel for separate traction and flux conditions.

Added: Force scalar parsing of neumann condition if direction > nsd

---

src/ASM/ASM2D.C
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DTri.C
src/ASM/ASMs2DTri.h
src/SIM/SIM2D.C
src/Utility/ElementBlock.C
src/Utility/ElementBlock.h
src/Utility/TriangleQuadrature.C
src/Utility/TriangleQuadrature.h
src/Utility/VTF.C

This adds support for 2D patches with triangular Lagrange elements (currently linears only, but extendable).
Includes #112 also, so merge that one first.

Triangle patches

---

src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

useful when writing vector fields derived from a scalar equation.
noticed while wanting to output the derived velocities in the darcy application as a vector field.

changed: allow specifying number of components in vector field

---

Apps/Common/EqualOrderOperators.h
Apps/Common/SIMExplicitRKE.h
Apps/Common/TimeIntUtils.C
src/Utility/BDF.C
src/Utility/BDF.h

used cmp instead of nsd.
second commit adds theta to the time integration order table, and the third makes the bdf extrapolate function more useful.
finally the missing adaptive loop is added to SIMExplicitRKE and the bogacki-shampine rke coefficients are fixed.

fixed: the scalar laplacian residual operator

---

README.md

Added the commands to install HDF5 as of Issue #133.
Also removed a lot of other packages which are not needed to build the IFEM simulation module.
I guess they were used only when the modeling tools were based on GoTools as well? But now I understand the new Python module is GoTools free.
But please correct me if wrong...

Updated README.md on the dependent modules

---

src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

Equvialent to writeGlvV, but output as fringe plot instead of vectors.
Used in OPM/IFEM-OpenFrac to dump the phase field residual as a scalar field.

Added: An overloded writeGlvS method that writes a single scalar field

---

src/SIM/SIMdependency.C

if number of components differ, the fields classes now
takes care of extracting the required components from the
full patch vector.

fixed: extract the entire patch vector for fields

---

Apps/Common/SIMMultiPatchModelGen.C
Apps/Common/SIMMultiPatchModelGen.h
src/SIM/ModelGenerator.h
src/SIM/SIM1D.h
src/SIM/SIM2D.h
src/SIM/SIM3D.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMgeneric.C
src/SIM/SIMgeneric.h
src/SIM/SIMinput.h
src/SIM/SIMoutput.C

The first commit is more or less cosmetic, except for the propagation of the checkRHS flag.
The other two are changes needed to handle nodal loads correctly in multi-patch models.
External nodal loads are used in Elasticty apps only, so others should not be affected.

Fixes for correct handling of nodal point loads in multi-patch models

---

Apps/Common/AppCommon.h
Apps/Common/SIMCoupled.h
Apps/Common/SIMCoupledSI.h
Apps/Common/SIMExplicitRK.h
Apps/Common/SIMSemi3D.h
Apps/Common/SIMSolver.h
Apps/Common/SIMSolverAdap.h
Apps/Common/SIMSolverTS.h
Apps/Common/Test/TestSIMCoupled.C
src/ASM/ASMunstruct.h
src/LinAlg/MatVec.h
src/LinAlg/matrix.h

After the very nice restart refactor, I think this follows naturally. It will make sense to let SIMSolver also handle the result output as well as restart such that you don't need the static method in AppCommon.
Downstream changes are modest, and ready, and will be pushed to respective branches after general acceptance of this one. But maybe @akva2 have something to say on it first.

Output refactor

---

src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h

Another convenience method. Using this in the alternative Kirchhoff-Love integrand, where outer_product of columns of d2NdX2 are needed.

Added: An extra matrix3d method + test

---

src/SIM/ModelGenerator.C
src/SIM/Test/TestModelGenerator.C

The single-patch 1D model generator produce incorrect geometry if you specify X0.
This is a proposed fix to that.

Fixed: 1D default geometry with nonzero X0

---

src/Utility/ExprFunctions.C

Assume Voigt notation ordering also when parsing expression functions for symmetric tensors.
To be consistent with the SymmTensor documentation.
This also fixes #87.

Voigt fix in STensorFuncExpr

---

Apps/Common/Test/TestMultiPatchModelGenerator.C
Apps/Common/Test/refdata/modelgen2d_lr.xinp
Apps/Common/Test/refdata/modelgen3d_lr.xinp
src/ASM/ASM2D.h
src/ASM/ASM3D.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs2DmxLag.C
src/ASM/ASMs2DmxLag.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h
src/ASM/ASMs3DmxLag.C
src/ASM/ASMs3DmxLag.h
src/ASM/ASMunstruct.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/SIM/SIM2D.C
src/SIM/SIM3D.C

This adds support for multipatch LR models in a very naive way. It has only been tested to work for tensor-converted models and I suspect it to crash and burn for more realistic models.
Opening early so you can look at it. I do not anticipate large changes to this part of the code, the major expectation being that we likely need to sort the nodes on the edges for generic models.
@kmokstad this is interface changes, input on that bit appreciated in particular.

Support multipatch LR models

---

Apps/Common/SIMSolverAdap.h
src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h

Suggest this cleanup to reduce potential confusion:
* The initAdaptor and writeGlv methods no longer use the nNormProj argument, which means that the getNoNorms method is not needed either.
* The getNormPrefixes method is not needed. There is no point in passing the projection names as prefixes to the HDF5-exporter, because norms of the projected solutions are not exported to HDF5 as it is implemented now (only for FE solution and analytical, when existing). If we also want to have norms of projected solutions on HDF5, this has to be implemented in a different way (do the solutionNorms call outside the exporter method, and only pass the resulting arrays, like we do for the solutions themselves. This, eventually, has to be a separate PR, though, not that urgent).
* The setupProjections …

Changed: Cleaned away some unused/defunct items from AdaptiveSIM

---

src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/SIM/SIMoutput.C
src/Utility/Tensor.C
src/Utility/Tensor.h
src/Utility/Test/TestTensor.C

For problems with rotational DOFs, we want to print out the absolute rotation angles for the result points (as in FENRIS).

Added: Extract total rotation angles for result point print

---

src/ASM/ASM1D.C
src/ASM/ASM1D.h
src/ASM/ASM2D.C
src/ASM/ASM3D.C
src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1DLag.C
src/ASM/ASMs2D.C
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DTri.C
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2DmxLag.C
src/ASM/ASMs3D.C
src/ASM/ASMs3DLag.C
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3DmxLag.C
src/ASM/Integrand.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3D.C
src/SIM/ForceIntegrator.C
src/SIM/SIMbase.C
src/SIM/SIMinput.C

This (the last commit) is work in progress. See detailed explanation in that commit message.
Not 100% sure if this is the best way of doing this in a general way, but is the best I came up with now.
The drawback is that the initElementBou signature is changed, requiring all apps that override that method to be updated. So far only supported for 2D non-mixed tensor splines. Will complete for others (and downstream updates) if/when the general concept is accepted.

Neumann extension

---

Apps/Common/SIMNodalConstraint.C
Apps/Common/SIMNodalConstraint.h
src/ASM/IntegrandBase.C
src/ASM/IntegrandBase.h
src/LinAlg/SAM.C
src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMinput.h
src/SIM/Test/TestSIM.C

Only the first commit might be controversial, but I think the simplification is OK? Did not see any practical reason why not the apply method could not me a member of SIMNodalConstraint (but please bear with me if there are some template magic here I don't see). At least the unit tests still passes.
The other fix only affects models containing multi-point constraints (master-slave couplings) and calculates reaction forces, essentially only the C1-plate problems, as far as I know.

External energy fix and SIMNodalConstraint simplification

---

scripts/log2reg.sed
src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2DC1.C
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/GlbL2projector.C
src/ASM/GlbL2projector.h
src/ASM/LR/ASMu2Dmx.h
src/LinAlg/matrix.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoutput.C
src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Function.h
src/Utility/SplineUtils.C
src/Utility/SplineUtils.h
src/Utility/TensorFunction.h
src/Utility/Test/TestSplineUtils.C
src/Utility/VTF.C

This unifies the projection of scalar and vector functions into one set of methods, and this is now used in a general method for projection of the analytical secondary solution for verification purposes.
Also, the result point/line output is enhanced to also handle recovered solution fields.

Anasol projection

---

Apps/Common/SIMSolverAdap.h
src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoptions.C
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

@akva2 se om du evt. kan få til det du trenger på toppen av dette. Her har jeg forsøkt å ta høyde for at norm gruppe 1 (som da inneholder eksakt feil når de finnes, kan inneholde noen flere størrelser og man kan velge mer fritt (via adNorm variabelen, `<use_sub_norm>` i input-filen) hvilken som skal brukes for adaptering. Dessuten en virtuell metode getRefereneNorm som returner normen det skal normaliseres med. Denne må da overlagres i din sub-klasse når det avvikes fra default implementasjon.
Så er det innført konseptet med at projection-metode NONE kan brukes til å angi en norm-gruppe som ikke har noen tilhørende projeksjon, men bare pure residuals. Angi `<residual\>`i input-filen (evt. kommand-linje opsjon `-residual` for å aktivere. Da tror jeg resten skal gå av seg selv, gitt at de …

Norm group facilitation

---

src/SIM/NewmarkSIM.C
src/SIM/NonLinSIM.C

Do only one iteration if the first iteration already satisfies the
convergence tolerance when refNopt=ALL. No check on subiter&FIRST here.
This only removes some unnecessary iterations in cases with sub-iterations, and may affect tests on apps using that feature (but hopefully only to the better).

Fixed: Partly undo of commit 89faa82c6f972e01029f2ec4e11f1f0e4865bdb2

---

Apps/Common/SIMSemi3D.h
Apps/Common/Test/TestMultiPatchModelGenerator.C
src/SIM/HHTSIM.C
src/SIM/NewmarkNLSIM.C
src/SIM/NewmarkSIM.C
src/SIM/NonLinSIM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/Test/TestSIM.C

Its default value (false) was not used in practice and it was
thus only a potential source of confusion.
Fixed: Also include the 'X'-nodes (if any) when counting the nodes
associated with the first basis. That means, we assume that only
the first basis can have Dirichlet boundary conditions defined in
local coordinate axes.
If you pull this one before #175, the unresolved problem mentioned there regarding the local coordinate system nodes should be fixed, I think. At least, this is a proposed solution to it.

Changed: The bool argument of SIMbase::getNoNodes is removed.

---

src/ASM/DomainDecomposition.h
src/ASM/Interface.h
src/SIM/SIM1D.C
src/SIM/SIM2D.C
src/SIM/SIM3D.C

will be reused for intra-process connection representations

changed: move Interface class out of DomainDecomposition

---

src/ASM/ASMbase.C
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/SIM/SIM2D.C

This adds the input-file tag `<collapse>` for 2D patches, which can be used when you have a polar parametrization where one of the edges collapse into a point. This then automatically assigns a common node number of all the collocated control points (replaces functionality formerly found in the getGNO utility). The extension to 3D (face to point and face to edge) is not there yet (but can be added).
I did this for the quarter-circular patch, which I ended up not using now after all, but...

Collapse degenerated edges into a single node

---

src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h

This resolves the memory issue http://afem:8000/job/IFEM-memtest/1010/
The problem is that AdaptiveSIM keeps an array of C-pointers to the norm prefices to use, but when the mesh is refined and the input-file is parsed again for the new mesh, these pointers are invalidated (at least when run through valgrind). Now I make a copy of those strings instead and the problem vanishes. Maybe not the most elegant, but works.

Fixed: Copy the norm prefixes to avoid valgrind complaint

---

Apps/Common/SIMCoupled.h
Apps/Common/SIMCoupledSI.h

It feels unnecessary and confusing with two versions of solveStep
and the need for the using statement when one of them is overridden?
I think the reason for the May 5th commit on this is that it was forgotten up update the overridden solveStep method in the one and only downstream application that did override it (SIMKEpsilonBase).
I believe it is much better(?) to update that signature also such that we don't need to overload this method, and consequently can skip the annoying need for using-statements.

Changed: Undo of 02d84c07e2dc79d3adeec067a47c5fe8d878f3ce

---

Apps/Common/SIMCoupled.h
Apps/Common/SIMCoupledSI.h
src/ASM/ASMu2DLag.C
src/ASM/ASMu2DLag.h
src/ASM/Test/TestMatlabPatch.C

It seems like the unordered_map class does not work as I anticipated. It do sorts on the key which makes the unit test on Matlab input fail (first commit). In the second commit I replaced by a vector of pairs instead which works better.
Is this a bug in STL or is it supposed to work like this?

Nodeset fix

---

src/SIM/NonLinSIM.C

this allows to print but not apply time stepping control

changed: print CFL for negative maxCFL value

---

src/ASM/LR/ASMu3D.C

Bezier functions were evaluated at the wrong parametric points. The proposed solution creates a bezier-element on  the interval [umin,umax] (as given by the current element) instead of [-1,1]. This means less chain rule differentiation on derivatives as well (I know someone that is wanting bezier-second-derivatives in the near future).

Bugfix: 3D-LR projection (CGL2) bezier evaluation was wrong

---

.gitignore
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Drecovery.C

This was missing, I think, so overrriding the ASMbase::evaluate method and invoking the L2-projection for both 2D and 3D.
The other changes in this PR are pure cleanup issues (needs testing though).

Interpolation of initial condition for ASMu[23]D

---

src/SIM/SIM2D.C
src/SIM/SIM3D.C

they are necessary in parallel, and depending on how the model is partitioned, they may be process-local. we should just ignore them.

fixed: lower-dimension connections is not an error

---

src/ASM/ASMmxBase.C
src/ASM/ASMmxBase.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs3Dmx.C

this is two field formulation with C^{p+1}/p and C^p/p-1 bases, but where the first basis has
an additional subdivision of each element.
this is an inf-sup stable basis for Stokes.
this required rewriting the MNPC establishment for tensor splines, previous implementation assumed the same element structure for all grids.

add support for sub-grid mixed elements

---

src/ASM/GlbL2projector.C
src/ASM/GlbL2projector.h
src/LinAlg/PETScMatrix.C
src/LinAlg/PETScMatrix.h
src/SIM/SIMinput.C

This adds support for using PETSc solvers for global L2 projections and the necessary functionality in the PETSc code (solve system directly built using elem map from SparseMatrix).

add support for solving global L2 systems using PETSc solvers

---

src/ASM/ASMbase.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2DIB.C
src/ASM/ASMs2DIB.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h
src/ASM/FiniteElement.h
src/ASM/Integrand.h
src/ASM/Interface.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/Test/TestASMu2D.C
src/SIM/AdaptiveSIM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

This generalizes some concepts from Immersed Boundary calculations and use these to allow for jump terms in norm integrands.
See https://github.com/sintefmath/IFEM-Stokes/pull/75 for user side.

Add support for jump terms in norm integrands

---

src/ASM/ASMunstruct.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h

this was only used in the previous incarnation of the code. i see no reason to keep it.

remove unused LR multipatch code

---

src/SIM/SIMoutput.C

e.g. boussinesq was missing the temperature

fixed: write all scalar anasols to VTF

---

src/ASM/ASMunstruct.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/Test/TestASMu2D.C
src/ASM/LR/Test/TestASMu3D.C
src/Utility/LagrangeInterpolator.C

- Found some issues while writing tests (included).
- virtualize various methods on ASMunstruct level and implement for 3D LR
with this, only minor adjustments in IFEM-OpenFrac (use through virtual interfaces) will allow for running adaptive 3D.

Fix 2D gauss point transfer and add 3D implementation

---

src/Utility/FieldFunctions.C
src/Utility/FieldFunctions.h
src/Utility/HDF5Writer.C

Kun siste commit, de andre er inkludert i #219 og #226.
Har utvidet funksjonaliteten i FieldFunction klassene til også ta høyde for tiden `t`, slik at riktig datasett leses inn når `t` endres i evaluerings-kallet. Ser ut til å fungere, men jeg fikk ikke til å ta høyde for adapterte grid, dvs. den antar nå at basisen er lik for alle t. Prøvde å bruke `HDF5Writer::hasGeometries` men den returnerte alltid false. Dette er derfor kommentert ut.

Anasol fields, now also with time histories

---

Apps/Common/SIMSemi3D.h
Apps/Common/SIMSolver.h
Apps/Common/SIMSolverAdap.h
Apps/Common/SIMSolverTS.h
Apps/Common/SIMconfigure.h

This class only contains the output handling and no time-stepping.
The SIMSolver and SIMSolverAdap templates then inherit SIMSolverStat,
adding time-stepping/restart and adaptive functionality, respectively.
This makes it clear that SIMSolverAdap is not for time-dependent problems.
Also moved the ConfigureSIM template to a separate header file.
This was something I was doing last spring while working on the residual error estimates for recovered solutions, but it was not merged then. Now, in the new year I want to clean this up before going too far. It has some downstream impact though (hopefully to the better).

Added: New solver template for stationary problems, SIMSolverStat

---

src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoptions.h

Just some convenience methods. Also (first commit) an extra argument for the SIMbase::project method such that it can be used when we only want a specified component.

Trace operator for matrix and matrix3D

---

src/ASM/ASMs2Dmx.C
src/ASM/LR/ASMu2Dmx.C

if not, we cannot apply boundary conditions for simulators where
number of fields > nsd. fixes boussinesq application.

fixed: ASMbase needs the maximum number of components

---

src/LinAlg/ProcessAdm.h

quells warnings about deleting object with virtual members and
non-virtual destructor

fixed: this should not be virtual

---

src/ASM/LR/ASMu2D.C

the data structure is O(n) for access (and O(1) insert). 
@kmokstad should fix observed inefficiencies in openfrac + hdf5 export.

fixed: iterate over basis functions instead of getting by ID

---

src/SIM/SIMoutput.C

This is necessary with Chorin. Due to the split nature of things, we do not have a pressure in the primary field when storing the VTF (it's written by the pressure correction SIM).
This causes problems, as the anasol still holds the pressure (necessary for norm calculations) and this sanity check comes to the rescue. Should only add sanity in any case so i think it's an acceptable solution.

fixed: make sure we have a row to store anasol component in

---

src/ASM/ASMunstruct.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/SIM/SIM3D.C
src/SIM/SIM3D.h
src/SIM/SIMinput.C
src/Utility/NodeVecFunc.C
src/Utility/NodeVecFunc.h

Some refactoring to make SIMinput cleaner.
There are two issues with this one that need some attention before this can be merged.
1. In ASMu2D::InterfaceChecker::Intersection (which I now changed into a std::pair, was done before the doxy arrived), I cannot see that the continuity flag (now the first member) is ever set or used. It is referred in the Stokes-app (the JumpCheckeru2D class), but where is it defined?
2. The second commit (SIM3D::clonePatches was missing) causes the 3D FSI tests to fail, due to the results are slightly off. Need to check whether it is the new or the old results that are the "correct" ones, and either update the tests for find the source of the error.

Move patch-only dependent code from SIMinput to ASM-scope

---

src/ASM/ASMs1DC1.C
src/ASM/ASMs2DC1.C
src/SIM/SIMinput.C

Correct enforcement of clamped boundary conditions for C1-patches not possible without this fix.
I guess some wiki-documentation on the dof-flag is in place also. Otherwise this is hard to decipher for others. Will be added later..

Fixed: Interpretation of the dof flag when constraining C1-patches

---

Apps/Common/MeshUtils.C
Apps/Common/Test/TestMeshUtils.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoutput.C
src/SIM/Test/TestSIM.C
src/Utility/HDF5Writer.C
src/Utility/HDF5Writer.h

Sending in the patch pointer instead of the index, since most uses of these methods are in a loop over patches and not in a random order. Then the search for existing patch is unnecessary.

Minor extract/inject patch solution refactor

---

Apps/Common/MeshUtils.C
Apps/Common/Test/TestMeshUtils.C
src/ASM/ASMunstruct.C
src/ASM/ASMunstruct.h
src/ASM/LR/ASMLRSpline.C
src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoutput.C
src/SIM/Test/TestSIM.C
src/Utility/HDF5Writer.C
src/Utility/HDF5Writer.h

The first two commits are the same as #267.
The other two to facilitate adaptive analysis of a plate with a center point load.
Since we are not guarantied that the refined mesh will include the control points of the starting mesh, we need to find the closest control point instead to apply the load at (approximation that will converge as the mesh is refined under the load, hopefully).
Besides, there was a bug in the threadGroup generation in that the old groups were not nullified when refining the mesh (why has this not been ans issue before)?
Finally (last commit), introduce option to specify the precision in norm and component output, also when running adaptively.

LR find closest node

---

src/Utility/HDF5Writer.C
src/Utility/HDF5Writer.h

- use the new H5Lexists convenience function
- explicitly use hid_t. 1.10 broke compatibility with ints.

fixed: support hdf5 1.10 library

---

3rdparty/stb_image.h
CMakeLists.txt
cmake/Modules/FindIFEM.cmake
src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMunstruct.h

This method can be used both in #161 and by SIMElasticity in when checking that the parameterdomain is valid for the Image material stuff.
Also the stb_image.h header file is moved to the 3rdparty folder, where all such code that we use in our projects should be placed, to keep it tidy.
If you agree..

Added: virtual method ASMbase::getParameterDomain

---

src/ASM/IntegrandBase.h
src/ASM/SAMpatch.C
src/ASM/SAMpatch.h
src/ASM/SAMpatchPETSc.C
src/ASM/SAMpatchPETSc.h
src/LinAlg/SAM.C
src/LinAlg/SAM.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h

To be used in norm calculations, etc. for monolithic coupled solvers.
As discussed before lunch today. Here is my suggestion on how to solve the norm calculation issue in case of non-mixed coupled simulators, through the introduction of the `dof_type` array in SAM (similar as `nodeType`, but size `ndof` instead of `nnod`). Not totally finished. Think there are some issues regarding the `SAM::normInf` method.

Added: Separate array dof_type to assign type flags on the DOF-level.

---

Apps/Common/scripts/regtest.sh.in
src/SIM/SIMsolution.C
src/SIM/TimeStep.C
src/Utility/HDF5Writer.C

if not, the stream is not finished when we read out the data

fixed: due to RAII usage in libcereal archive must go out of scope

---

src/ASM/ASMstruct.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Drecovery.C

This fixes #301 because the assembly methods require the global element numbers, where the findElementContining methods returns local patch-wise element indices (including the 0-elements).
The other commit here is some LR cleanups from April.

 Fixed: Pass global (not local) element number to the SAM assembly methods

---

src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs1DLag.C
src/ASM/ASMs2D.C
src/ASM/ASMs2Dmx.C
src/ASM/ASMs3D.C
src/ASM/ASMs3Dmx.C
src/ASM/ASMstruct.C
src/ASM/ASMstruct.h
src/ASM/Fields.C
src/ASM/Fields.h
src/ASM/IntegrandBase.C
src/ASM/IntegrandBase.h
src/ASM/SplineFields1D.C
src/ASM/SplineFields1D.h
src/SIM/SIM1D.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h

Revised part of #316 concerning 1D models.
The input is here handled in a slightly different way. Instead of an extra attribute on the refine/raiseorder tags, a separate `<projection>`-tag within the `<geometry>`scope is introduced, where commands that should apply to the projection basis are specified.

Separate projection basis for 1D

---

src/ASM/ASM1D.h
src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs1DC1.C
src/ASM/ASMs1DC1.h
src/ASM/ASMstruct.C
src/ASM/HHTMats.C
src/ASM/NewmarkMats.C
src/SIM/SIM1D.C
src/SIM/SIM1D.h

This (last commit) adds the support for boundary conditions in skew coordinate systems for 1D patches.
The local axes are calculated with the tanget direction as the local X-axis, the the binormal vector (that is, the normal vector of the plane of curvature) as the local Y-axis. If the curve is straight, the local Y-direction is chosen arbitrarily.
There is a potential issue when it comes to fixing rotations for C1-patches, where the local directions are are imposed to the second control point. What is the tangent (and binormal) directions here? Currently, we use the same as for the end point, but this might not be strictly correct unless the two points are very close to each other, or the curvature is very small.

Boundary conditions in local axis directions for 1D

---

src/ASM/ASMmxBase.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Dmx.C
src/Utility/SplineUtils.C
src/Utility/SplineUtils.h
src/Utility/Test/TestSplineUtils.C

Previously we established a full-continuity basis for projection in these cases. We now keep the reduced continuity lines in the projection basis.
There is one caveat; we cannot automate this procedure when geometry is linear. In that case, a separate projection basis has to be specified through the <projection> keyword in the files.
I think this is a better compromise, the alternative is to flip the mixed establishment completely; have user give the highest order basis, and then establish the pressure basis through lowering order instead. This would require updating every single mixed setup already existing.

Fixed mixed adaptive simulations on meshes with reduced continuity

---

Apps/Common/MultiPatchModelGenerator.C
src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2DC1.C
src/ASM/ASMs2DC1.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs2DmxLag.C
src/ASM/ASMs2DmxLag.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h
src/ASM/ASMs3DmxLag.C
src/ASM/ASMs3DmxLag.h
src/SIM/SIM1D.C
src/SIM/SIM1D.h
src/SIM/SIM2D.C
src/SIM/SIM3D.C
src/SIM/SIMinput.C

* In the first commit, the beam-specific features are removed (they are now placed in the SIMElasticBar class instead), since this has relevance for elastic beam applications only.
* In the second commit, the periodicity input handling is moved to SIMinput and a virtual method in ASMbase is introduced to avoid casting the spline patch object when applying the periodicity conditions.

Some cleaning of the SIMxD classes

---

Apps/Common/MultiPatchModelGenerator.C
Apps/Common/MultiPatchModelGenerator.h
Apps/Common/Test/TestMultiPatchModelGenerator.C
src/ASM/ASMs1D.C
src/ASM/ASMs2D.C
src/ASM/ASMs3D.C
src/ASM/FiniteElement.C
src/ASM/LR/ASMu2D.C
src/ASM/Test/TestMatlabPatch.C
src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h
src/SIM/ModelGenerator.C
src/SIM/ModelGenerator.h
src/SIM/SIM1D.C
src/SIM/SIM1D.h
src/SIM/SIM2D.C
src/SIM/SIM2D.h
src/SIM/SIM3D.C
src/SIM/SIM3D.h
src/SIM/SIMdummy.h
src/SIM/SIMgeneric.C
src/SIM/SIMinput.C
src/SIM/SIMinput.h
src/SIM/Test/TestModelGenerator.C
src/Utility/Test/TestCoordinateMapping.C

A convenience for small models that are not easily covered by the model-generator.
Did this last fall, then almost forgot it. But think it is nice-to-have functionality.
The others here are minor things.

Support for spline patch definition in the xinp directly instead of via file

---

src/Utility/StbImage.C
src/Utility/StbImage.h

the header can only be used once. we need this wrapper
class with multiple texture material types.

added: singleton entry point for stb image

---

src/SIM/ModelGenerator.C
src/SIM/SIMargsBase.C
src/SIM/SIMargsBase.h
src/SIM/XMLInputBase.C
src/SIM/XMLInputBase.h

when the included file contains for than one tag, to ensure they are inserted into the right place.
Added: Debug print of the expanded XML-file content.

Fixed: Use InsertAfterChild instead of LinkEndChild in XMLInputBase

---

src/ASM/ASM3D.h
src/ASM/ASMbase.h
src/ASM/ASMs1D.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/Test/TestASMs2D.C
src/ASM/Test/TestASMs3D.C
src/SIM/SIM2D.C
src/SIM/SIM3D.C

Changed: Removed the basis argument in the constrainNode method
in ASMs3D to be compliant with the ASMs2D method (they are not
in use for mixed problems). Also some minor doxy corrections.
Added: Unit tests for the collapse methods for ASMs2D and ASMs3D.
This might be needed for Arcon's testing.

Added: Optionally collapse degenerated faces into an edge or node.

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/LRSplineField2D.C
src/ASM/LR/LRSplineField3D.C
src/ASM/LR/LRSplineFields2D.C
src/ASM/LR/LRSplineFields3D.C
src/ASM/LR/Test/TestASMu2D.C

Same as first commit of #352, but also with similar fix for the projection basis in ASMu2D.
Otherwise, one of the Kirchhoff-tests using separate basis for projection still crashed.
Need this now since VikingScientist/LRsplines#28 has been pulled and installed on the apt repository.

Changed: Make sure we generate IDs for LR objects

---

src/ASM/LR/ASMu2D.C

Fixes #347 which apparently was caused by this workaround.
Should probably revisit this later for a proper fix, but as this keeps popping up randomly for the multi-patch VCP test, I think we should merge this first. So far only one downstream regression is affected.

Fixed: Undo the fix in e69c100b17d0e5cd59d3d4cb7efe3fa1302754c7

---

src/SIM/SIMoutput.C
src/Utility/VTF.C
src/Utility/VTF.h

This also fixes the annoying vanishing meshlines in GLviewInova
when using the slide bar to go from one step to the next, and
avoids the freeze of Ceetron Analyzer when selecting another step.

Fixed: Don't increment part ID for adaptive grids.

---

src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMunstruct.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMLRSpline.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h
src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h
src/LinAlg/matrixnd.h
src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h
src/SIM/AdaptiveSetup.C
src/SIM/AdaptiveSetup.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMinput.C
src/SIM/SIMinput.h
src/SIM/SIMoutput.C

This contains some items that used to be in #346 which now is a bit long and untidy. That branch will be rebased on this later. The main point here is to split out the parameter setup and the error_norm-to-refinement_indicator calculations in a separate class, AdaptiveSetup, which then AdaptiveSIM inherit from.
The motivation is that AdaptiveSetup then also can be re-used in nonlinear/dynamic solvers which have their own time-stepping drivers, etc.

AdaptiveSIM refactor

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h

This is a leftover from #319. Without this, the L2-projection does not work for non-linear shell analysis as the NURBS weights are not accounted for when calculating the updated control point positions.

Fixed: Account for NURBS weights in ASMu2D::getNodalCoordinates also

---

src/SIM/SIMinput.C
src/Utility/Functions.C

Instead of `<neumann type="generic" direction="-1">(something)</neumann>`.
With this, I'm not sure if we actually need type="generic" any more (are any of the "generic" neumann conditions still around something else than robin conditions)?

 Added: XML-tag <robin> for the Robin-type boundary conditions 

---

src/ASM/ASMs2D.C
src/ASM/Interface.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/SIM/SIMbase.C

This adds the interface integration functionality also in assembleSystem (currently it is invoked for solutionNorms only). The motivation is to use this for right-hand-side calculation due to line loads along interior mesh edges for plate and shell problems.
Does not work yet, and time is running up before NSCM-31 next week. Just creating this PR for picking up at a later point. Remaining issues:
* Currently, many of the LinEl tests fails with nodes out of range during norm integration. Think it is due to the lambda functions, but not sure why.
* Check the interface-integration methods for ASMs2D, ASMu2Dmx and now ASMu2D. They look too different.
* Add an ASM::InterfaceChecker sub-class in SIMLinElKL to actually represent the line load.

Interface integration in SIMbase::assembleSystem

---

src/LinAlg/ISTLMatrix.C

fixed: ISTL(Matrix|Vector) copy constructors

---

src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/Utility/HDF5Writer.C

so we can output these to hdf5. these are required when doing reduced
order models. this makes it easy to obtain them without having to use
hackery every time.

added: also store the eigen modes in equation ordering

---

src/SIM/SIMoutput.C

we only dereference the second entry, so no reason to require
size to be 3

fixed: index check

---

src/Utility/Test/TestTriangleQuadrature.C
src/Utility/TriangleQuadrature.C

This fixes a typo in the 4 point triangle quadrature rule and adds a simple unit test.

Fix triangle quadrature

---

src/LinAlg/matrix.h
src/SIM/SIMbase.C
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

Also extended utl::vector::normInf to optionally account for the sign in its returned value.

Support computation of patch-wise maximum values

---

src/SIM/NewmarkNLSIM.C
src/SIM/NewmarkNLSIM.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoutput.C

This was added in 5f5d792c00b4ac7c77b9a732b4d4507a9f695036 but
will make global L2 projection fail for models with plasticity.
It appears that this commit from 2016 is not needed any more,
probably due to other changes/fixes elsewhere in the meantime.
Changed: Made setPatchMaterial const to avoid const_casting elsewhere.
Changed: Minor doxy-issues for extractPatchSolution.

Fixed: Don't call initResultPoint in the project method

---

CMakeLists.txt
src/LinAlg/LinSolParams.C
src/LinAlg/PETScMatrix.C
src/LinAlg/PETScSchurPC.C
src/LinAlg/PETScSchurPC.h

previously only the SIMPLE (i.e. diagonal of A) approximation was
possible. now, any approximation can be used for A^-1.

added: full support for schur-complement block preconditioners

---

src/LinAlg/SparseMatrix.C

added: handle multiple right hand sides in umfpack solve

---

src/ASM/ASMs1D.C
src/ASM/ASMs2D.C
src/ASM/ASMs3D.C

It turns out I was wrong in e3da110cb9ea7f4fa3634257f64abcdf531782eb (see my review in #371).
The check should instead use the number of coefficient in the patch, which will work both for mixed and regular problems. The check against `MLGN.size()` is still needed as a secondary condition, in case of Dirichlet conditions in local axes (with extra nodes around).

Fixed: Incorrect sanity check correction

---

src/IFEM.C
src/IFEM.h.in
src/SIM/SIMoptions.C
src/SIM/SIMoptions.h
src/SIM/SIMoutput.C
src/Utility/Profiler.C

This (the SIMoutput fix) is needed for the digital-twin model, for instance, when there are more than one result points and not all one the same patch. The other commit is more cosmetic, but enables the possibility run without the -controller also (for debugging, etc.)

Fixed: Result point evaluation for multi-patch models

---

src/SIM/NewmarkSIM.C
src/SIM/NewmarkSIM.h
src/SIM/SIMmodal.C
src/SIM/SIMmodal.h

This enables the possibility to run NewmarkSIM with SIMmodal in quasi-static mode,
by setting beta to zero, in which case there are no velocity and acceleration vectors around.

Quasi-static modal simulation when beta=0

---

src/ASM/ASMs2Dmx.C
src/ASM/ASMs3Dmx.C

Also provide spline parameters to the Vec4 object in the boundary
integration methods, to account for possible field evaluation there.
The remaining changes are cosmetics only.
This (partly) replaces #289 which has been rebased beyond its original state.
It will remove a memory leak from the mixed NonLinEl tests (tQ2-Q1 and Q2Q1).
Have also tried to make the 2D and 3D implementations more similar to ease comparison.
Guess not that well covered by unit/regression tests yet, so please take look at it before approving.

Fixed: Memory leak in ASMs2Dmx::getBoundary

---

src/LinAlg/SparseMatrix.C
src/Utility/AnaSol.C
src/Utility/AnaSol.h
src/Utility/VTF.C

and make the parse[Expression|Field]Functions methods private.
Fixed: Avoid crash if the file attribute is forgotten.
This just some cosmetics that should not affect behavior, I hope..

Changed: Use a polymorphic lambda instead of the static function

---

Apps/Common/scripts/regtest.sh.in

In the restart regression tests, a restart hdf5-file is written in both the original execution, and in the restart. It is not needed in the latter, and it ends up in the source code tree where it does not belong.

Fixed: Avoid writing unnecessary restart file

---

src/SIM/SIMinput.C
src/SIM/SIMinput.h

This allows for the convenient syntax
```
<topologysets>
<set name="support" type="face">
<item lowerpatch="30" upperpatch="50">5</item>
</set>
</topologysets>
```
to define a set consisting of face=5 for all patches in the range 30 to 50.

Added: Support for lowerpatch and upperpatch attributes

---

src/SIM/SIMinput.C

use this to indicate that the two coefficients alpha and g are packed
as one vector function (alpha | g)

changed: allow specifying direction="-1" on robin conditions

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/SAMpatch.C
src/ASM/SAMpatch.h
src/ASM/SAMpatchPETSc.C
src/ASM/SAMpatchPETSc.h
src/LinAlg/SAM.C
src/LinAlg/SAM.h
src/SIM/SIMbase.C
src/Utility/MPC.C
src/Utility/MPC.h

Fixes #263 (I think).
The problem was incorrect resolving of the chained MPC-equations for time-dependent simulations, for instance for KL shell models with symmetry BC's resulting in constraints on the boundary tangent, and inhomogeneous dirichlet conditions at adjacent boundaries.
This now works, at least the test-model attached in #263 runs.

Fixed: Processing of chained MPCs for time-dependent problems

---

src/Utility/HDF5Base.C
src/Utility/HDF5Base.h
src/Utility/HDF5Restart.C
src/Utility/HDF5Restart.h
src/Utility/HDF5Writer.C
src/Utility/HDF5Writer.h

This (i.e., the last commit, the others of more cosmetic character), should fix the issue with bullshit projected stress fields from the LinearElasticity app. The problem was that the LinEl registers the projected fields in a separate loop (since there in theory can be more than one of them). But inside the HDF5Writer they are treated as the primary solution and projected once again. The result then became of order O(2n) of instead of O(n) (E+18 instead of E+9, etc.)
You need to very this comparing with direct VTF output before approving.

Fixed output of projected fields to HDF5

---

src/SIM/AdaptiveSetup.C
src/SIM/AdaptiveSetup.h

needed for (staggered) simulators where we want to handle the
printout ourself

added: flag to suppress simulator norm output in AdaptiveSetup::printNorms()

---

src/SIM/AdaptiveSetup.C

Useful to see the extras due to the symmetrization.

added: print actual percentage of functions marked with symmetrized beta

---

src/LinAlg/Test/TestPETScMatrix.C

for some reason newer PETSc requires an explicit call to zero out the
matrix.

fixed: TestPETScMatrix.Assemble

---

src/ASM/ASMs2D.C
src/ASM/ASMs3D.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3Dmx.C

Since multithreading and MPI (now) is usable at the same time, this creates a lot of terminal noise in parallel simulations.

changed: log multithreading info to IFEM::cout

---

src/ASM/GlbL2projector.C
src/ASM/GlbL2projector.h

Here is a rebased and slightly revised version of the second commit of #213

Changed: Use element matrices in global L2 for efficiency

---

src/Utility/DataExporter.h
src/Utility/HDF5Writer.C
src/Utility/HDF5Writer.h

this is on a per-basis level, ie, not interleaved on a per-patch
basis as used in IFEM

added: support for saving the local-to-global node mapping in HDF5

---

Apps/Common/SIMSolver.h

this matters because it holds information about the partitioning.
in particular, this is necessary to get correct results with graph
partitioning.

fixed: pass the correct process admin to the hdf5 writer

---

src/SIM/AdaptiveSetup.C

This came up in adaptive simulations. The LRSpline library has a tolerance to classify basis functions as equal.
With extreme corner refinement the default tolerance is too big. This allows for customization through
the input file. 
Requires an updated LR spline library to function, but it is safe for merge as it has an ifdef protection.

added: ability to customize LRSpline same-function tolerance

---

src/ASM/LR/ASMu3D.h

this was forgotten in the original commit. after a review
comment myElms were added to ASMbase, and I forgot
to remove it in ASMu3D.

fixed: remove unnecessary myElms member in ASMu3D

---

src/SIM/SIMinput.C

cannot assume all vectors have the same amount of fields
as the simulator has primary dofs.
this broke adaptive fracturedynamics.

fixed: specify number of dofs for the solution

---

src/SIM/SIMinput.C

if we are shared, these are complete ignored further down. no reason
to calculate them.
useful for adaptive multi-patch fracture dynamics

fixed: avoid unnecessary expensive refinement parameter calculations

---

src/LinAlg/PETScSolParams.C

In particular this allows switching between mumps and superlu_dist without resorting to command line parameters.

fixed: set the package in petsc pc blocks

---

src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs2D.h
src/ASM/ASMs2Drecovery.C
src/ASM/ASMs3D.h
src/ASM/ASMs3Drecovery.C
src/ASM/GlbL2projector.C
src/ASM/GlbL2projector.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMLRSpline.h
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Drecovery.C
src/SIM/SIMbase.C

I need this in the Stokes application (to use projected source functions). And since I have separate projection bases there, the current support does not cut it.
@kmokstad I am sure you have some opinion here. I can do it however you see fit, this does the job...

added: (non-internal) L2 projection support for functions

---

src/SIM/SIMbase.h

256 refinements can happen, in particular in fracturedynamics.
this leads to overflow and a very confusing error message.

changed: make isRefined an int

---

src/SIM/SIMoutput.C
src/Utility/VTF.C
src/Utility/VTF.h

Using a class member variable that is incremented each time a geometry block is added, instead of trying to provide a valid partID, which turns out difficult with a variety of geometry block types around. (Element blocks, points for tractions, additional geometry, etc.) Unfortunately, it affects some downstream apps, so be on alert..

VTF geometry block admin change

---

src/ASM/ASMbase.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/Utility/Test/TestThreadGroups.C
src/Utility/ThreadGroups.h

With this the K-joint model with rigid couplings at the ends also works when using multi-threading.

Fixed: Account for boundary MPC couplings when choosing stripe direction

---

src/ASM/ASMbase.C
src/SIM/SIMbase.C
src/SIM/SIMoutput.C

This should (hopefully) fix hdf5- and vtf-export for such models.

Account for extra-ordinary nodes when extracting primary solution for patches

---

src/LinAlg/MatVec.C
src/LinAlg/MatVec.h
src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h

The first commit is to be used for input of superelement matrices (reduced-order-models).
The second commit fixes the local-to-global transformation of beam element matrices in IFEM-Elasticity.

Input stream operators for matrices and vectors and congruence transformation fix

---

src/ASM/IntegrandBase.h

To ensure consistent behavior when parsing app-specific input

Changed: Let IntegrandBase::parse() return false by default

---

src/ASM/ASMbase.C
src/ASM/LR/ASMLRSpline.C

This replaces the temporary fix OPM/IFEM-OpenFrac#55.
Whenever the mesh is refined, the existing FE topology structures are no longer valid and should be cleared.
For shared patches, one must also clear the shared arrays (MLGN, MLGE and MNPC).

Fixed: Clear all (including shared) FE arrays after refinement

---

Apps/Common/SIMSolver.h
Apps/Common/SIMSolverTS.h
src/Utility/DataExporter.C
src/Utility/DataExporter.h

The first commit here is a polished version of #469.
Then a proposed solution to the mismatching time level flags on hdf5-files for restart and visualization in restart runs.
Now we use the time level specified for the restart as the initial time level for the DataExporter, instead of always starting from 0.
Perhaps a similar approach should be used from HDF5Restart as well (there istep and stride are used to compute the time level, which will yield incorrect results if the stride is changed in a restart, not an unusual scenario).

Changed: Set initial time level for restart runs from previous

---

Apps/Common/SIMSolverAdap.h
src/ASM/ASMsupel.C
src/ASM/ASMsupel.h
src/SIM/SIMbase.C
src/SIM/SIMsupel.h
src/Utility/DataExporter.C
src/Utility/DataExporter.h
src/Utility/HDF5Writer.C

In addition (see second commit), the element norm prefixes are now extracted from the SIM objects instead of storing them separately in the writer class. This is to simplify the HDF5 setup, especially for the multi-dimensional coupled elasticity simulator (see OPM/IFEM-Elasticity#112).
Included here (third commit) is also #469.

Output of lagrangian mesh for superelement patches to HDF5

---

Apps/Common/ISolver.h
Apps/Common/SIMCoupled.h
Apps/Common/SIMExplicitLMM.h
Apps/Common/SIMExplicitRK.h
Apps/Common/SIMImplicitLMM.h
Apps/Common/SIMSolver.h
Apps/Common/SIMSolverTS.h
src/ASM/ASMbase.h
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.h
src/SIM/MultiStepSIM.C
src/SIM/MultiStepSIM.h
src/SIM/SIMbase.h
src/SIM/SIMinput.C
src/SIM/SIMinput.h
src/SIM/TimeStep.C
src/Utility/DataExporter.C
src/Utility/DataExporter.h
src/Utility/HDF5Restart.C
src/Utility/HDF5Restart.h

This replaces #449 with some improvements/fixes:
* The signature of the `restart` method is unchanged to avoid too may downstream changes.
Instead the `ProcessAdm` object is retrieved from the solver object.
* Methods for (de)serialization of bases is included in class `SIMinput`.
* Bases are stored as `<name>::basis` instead of `<name>-basis`
* `TimeStep::reset()` should not update `stopTime` if `istep > 0`.
* The reference norm of the Newton iterations are serialized.
* And some minor cosmetic changes.

Restart for time-slab adaptive simulations

---

src/SIM/SIMbase.C
src/SIM/SIMbase.h

...when extraordinary nodes and/or monolithic coupled simulators.
Not sure about side-effects here so, so be alert. Could also be the addMADOF() method should have been used.

Fixed: Use a separate MADOF array in extractPatchSolution()

---

src/ASM/ASMs2D.C
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3DLag.C
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMLRSpline.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/Test/TestASMs3D.C

This is needed for `<nGauss default="0"/>` to work properly when we have neumann conditions on 3D elements with different polynomial orders in the three parameter direction. Mostly for enabling correct export of traction vector arrows to VTF.

Fixed: Using direction-dependent Gauss quadrature on face integrals

---

src/LinAlg/DenseMatrix.C
src/LinAlg/DenseMatrix.h
src/LinAlg/DiagMatrix.C
src/LinAlg/DiagMatrix.h
src/LinAlg/LinAlgenums.h
src/LinAlg/SparseMatrix.C
src/LinAlg/SparseMatrix.h
src/LinAlg/SystemMatrix.C
src/LinAlg/SystemMatrix.h
src/SIM/SIMbase.h
src/SIM/SIMinput.C

Matrix-market format is useful for testing as it is supported by various linalg packages (in my case amgcl).

Add support for matrix/vector dumps in matrix-market format

---

src/ASM/LR/ASMLRSpline.h
src/ASM/SAMpatch.C
src/SIM/FunctionSum.C
src/SIM/NonLinSIM.C
src/SIM/SIM2D.C
src/SIM/SIMmultiCpl.C
src/SIM/SIMoutput.C
src/Utility/DataExporter.C
src/Utility/FieldFunctions.C
src/Utility/HDF5Restart.C

- const for keys
- std::move to avoid some copies
- a missing using statement

Fixes for warnings emitted by new clang/gcc versions

---

src/SIM/MultiStepSIM.C
src/SIM/SIMoptions.C
src/SIM/SIMoptions.h
src/SIM/SIMoutput.h
src/Utility/VTF.C

Adding `<saveTrac/>` within `<postprocessing>` which can be used by multi-step solvers to save tractions to VTF without having to save other secondary solution variables. And avoid writing traction points for the zero-knot-span elements. They didn't do any harm though, only contribute to unnecessary increased VTF-file size.

Traction output (to VTF) corrections

---

src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Test/TestFunctions.C

Used with CoSTA simulators to use an externally provided value in source functions etc.

added: ability to set a parameter value for ExprFunctions

---

src/SIM/NonLinSIM.C
src/SIM/NonLinSIM.h

To speed up linear multi-loadcase simulations (e.g., with `NonLinEl -linear`).

Fixed: Don't recalculate tangent in pure linear analysis

---

src/Utility/Profiler.C
src/Utility/Profiler.h

Useful for using IFEM in a stricter library context, like in Costa.

Changed: allow profiler to optionally be silent

---

Apps/Common/SIMSolverAdap.h
src/ASM/AlgEqSystem.C
src/LinAlg/DenseMatrix.C
src/LinAlg/DenseMatrix.h
src/LinAlg/DiagMatrix.C
src/LinAlg/DiagMatrix.h
src/LinAlg/ISTLMatrix.C
src/LinAlg/ISTLMatrix.h
src/LinAlg/PETScMatrix.C
src/LinAlg/PETScMatrix.h
src/LinAlg/SPRMatrix.C
src/LinAlg/SPRMatrix.h
src/LinAlg/SparseMatrix.C
src/LinAlg/SparseMatrix.h
src/LinAlg/SystemMatrix.h
src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h

The argument `newLHS` is not (or shouldn't be) needed, and therefore removed to lessen confusion. It was referred only by the `PETScMatrix` subclass, but also there the `factored` member of the parent class (`SparseMatrix`) can now be used. This flag is reset whenever the matrix is reinitialized by the `initAssembly()` method.
Consequently, the `newLHS` argument in `SIMbase::solveSystem()` can also go away, which have some downstream effects.
The fourth commit is unreleated, but makes better sense.

SysMatrix::solve argument cleanup

---

src/ASM/AlgEqSystem.C
src/ASM/AlgEqSystem.h
src/LinAlg/SAM.C
src/LinAlg/SAM.h
src/SIM/NewmarkSIM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoutput.C

Only to make clear this is not a `Vector` subjected to algebraic operations.

Changed: Use std::vector<double> as reaction force container

---

src/ASM/DomainDecomposition.C

- Print block matrix sizes in serial
- Put global lagrange multipliers in second block also with single basis method

Fix block matrix with single basis discretization

---

src/LinAlg/ProcessAdm.C

I guess at some point we did not dupe comms in serial, but we do now.

fixed: we need to free the MPI_Comms even in serial

---

src/SIM/NonLinSIM.C

allows suppressing norm and solution summary output, while still
keeping the iteration history. useful in split simulators
such as Chorin

changed: print iteration history in NonLinSIM even at msgLevel -1

---

src/ASM/BlockElmMats.C
src/ASM/BlockElmMats.h
src/ASM/Test/TestBlockElmMats.C

this way we can use its non-emptyness to signal that
it has already been assembled.

changed: do not resize the newton matrix up front

---

src/LinAlg/SparseMatrix.C

if we have previously reused the matrix factorization,
the FACTORED value is stored. this leads to segfaults.
we now properly flag that we only want to reuse the
sparsity pattern.

Fix SuperLU option

---

doc/Doxyfile.in
src/ASM/LR/ASMu3D.h

For circumventing a bug in doxygen for Ubuntu 20.04

Changed: Enable MathJax for equation rendering

---

src/ASM/ASMs2D.C
src/ASM/ASMs3D.C

in particular for mixed integrands using anasol boundary conditions
nf can be greater than the number of components in the function. this is
because nf is set to the total number of fields and not the number
of fields on a single basis

fixed: check number of components in function

---

src/SIM/AdaptiveSetup.C

Users keep getting this wrong. Having the alias is harmless..

changed: add 'symmetric' as an alias for 'symmetrized' beta type

---

src/SIM/SIMoutput.C

this is necessary to not register multiple functions if
used in adaptive simulations

fixed: clear additional functions in clearProperties

---

cmake/Modules/FindVTFWriter.cmake
src/ASM/ASMs3D.C
src/ASM/IntegrandBase.h
src/ASM/ReactionsOnly.C
src/ASM/ReactionsOnly.h
src/ASM/TimeDomain.h
src/LinAlg/SAM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMgeneric.C
src/SIM/SIMoutput.h

A general method SIMbase::assembleForces() is provided for the integration of reaction and/or interface forces, for the identified boundaries. The virtual method haveBoundaryReactions() need to be overridden by the application to decide which patches to be considered.

Generalization of reaction- and interface force calculation

---

src/ASM/IntegrandBase.C
src/ASM/IntegrandBase.h

previously there was no way to clear the buffers used during
integration. now initBuffer resizes only if necessary, but
always zeros the underlying buffer.
closes https://github.com/OPM/IFEM-Darcy/issues/51

changed: facilitate reuse of ForceBase derived integrands

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu3D.C
src/Utility/ElementBlock.C
src/Utility/ElementBlock.h

This is needed for models with internal C^{-1} lines, to properly visualize the discontinuity with deformed geometry.
Without it, one often picks the wrong nodal results along the discontinuity.

Added: Optional element shrinkage factor for LR meshes to VTF

---

src/ASM/ASMs2DInterpolate.C
src/ASM/ASMs2Drecovery.C
src/ASM/ASMs3DInterpolate.C
src/ASM/ASMs3Drecovery.C
src/SIM/AdaptiveSIM.C
src/SIM/SIMmultiCpl.C
src/SIM/SIMoptions.C
src/Utility/Utilities.C
src/Utility/Utilities.h

This (hopefully) silence the compler warnings detected by newer compilers in Build [#353](http://afem.sintef.no:8080/job/IFEM/353/). In addition, the signature of the static VariationDiminishingSplineApproximation() methods are simplified passing (pointer to) the spline object to project only instead of its components.

Quell newer compiler warnings

---

src/ASM/ASMbase.h
src/ASM/GlbL2projector.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3Dmx.h

Includes an option (currently hardcoded) to enforce the end-point values in the L2-projection.
Not very well tested - only in 1D, so this is WIP.

L2 refactor

---

src/ASM/LR/ASMu2Dmx.C

we also have to switch geometry as we need elements without the additional refinement when projecting the pressure

fixed: have to regenerate bezier basis when switching projection basis

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dnurbs.C

always take a spline pointer parameter. use reference in the NURBS interfaces.

changed: unify computeBasis signatures

---

CMakeLists.txt
src/LinAlg/ProcessAdm.C
src/LinAlg/ProcessAdm.h
src/SIM/SIMinput.C

calculate these on root node and broadcast instead of calculating
separately on each process. this can cause desync between processes,
for instance if the initial condition uses random numbers

fix initial conditions with partitioning

---

src/ASM/ASMs2Dmx.C
src/ASM/ASMs2DmxLag.C
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3DmxLag.C
src/ASM/FiniteElement.C
src/ASM/FiniteElement.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h

This originates from #397 more than 3 years ago, and contains some cleanup (including fix of potential issues) of the ASMu[23]mx code, but is not directly related to the scope of that PR. Motivation: Less code-duplication, and easiear to compare 2D and 3D implementations (diff).

Some cleanup of mixed LR

---

src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h

Introduce a method to obtain last node on integration basis and use this to deduplicate the methods that obtains parametric area/volume/length. Likewise introduce a method to obtain first node on integration basis and use this to deduplicate getElementCoordinates().

Some deduplication in ASMsxDmx

---

src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h
src/ASM/ASMsupel.C
src/ASM/ASMsupel.h
src/ASM/ASMu1DLag.C
src/ASM/ASMu1DLag.h
src/ASM/ASMu2DLag.C
src/ASM/ASMu2DLag.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h
src/Utility/FieldFunctions.C

Instead, introducing a separate `readBasis()` method.
Consider if this simplifies the logic, and does not break any future intentions.

Changed: Second (mostly dummy) argument in read method is removed.

---

src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMLRSpline.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2DC1.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu2Dnurbs.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h

This is stored as geomB in ASMstruct. Do the same in ASMLRSpline for consistency (and to facilitate further upcoming changes).

Unify geometry pointer in ASMLRSpline with ASMstruct

---

src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3Dmx.C

ASMuxDmx: simplify remapErrors by using elm->midpoint()

---

src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2DLag.C
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs2Drecovery.C
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3DLag.C
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h
src/ASM/ASMs3Drecovery.C
src/ASM/ASMstruct.C
src/ASM/ASMstruct.h

Make this consistent with other bases. This introduces some more casts than comfortable but they will go away later.

ASMsxD: move projection bases into ASMstruct

---

src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h

This to fix a bug with two-field formulations where the second basis is the higher order basis, and to prepare for having a separate geometry basis.
Sits on top of https://github.com/OPM/IFEM/pull/608

Override separateProjectionBasis()

---

src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3Dmx.C

Unnecessary copies has been used earlier due to lazyness, in particular to avoid bare pointer juggling.
Also unify structure of basis establishment between structured and unstructured ASMs, and fixes handling for ASMmxBase::REDUCED_CONT_RAISE_BASIS2  in the 3D LR ASM.

Avoid cloning in ASMsxDmx

---

src/ASM/ASMs2D.C
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs3D.C
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h
src/ASM/Test/ASMCube.h
src/ASM/Test/ASMSquare.h
src/ASM/Test/TestASMs2D.C
src/ASM/Test/TestASMs2Dmx.C
src/ASM/Test/TestASMs3D.C
src/ASM/Test/TestASMs3Dmx.C
src/ASM/Test/TestSplineFields.C

This removes some unnecessary overrides and adds tests for write/getBasis implementations in structured ASMs.

Unify ASMsxDmx and ASMsxD write methods

---

Apps/CMakeLists.txt
Apps/Common/CMakeLists.txt
CMakeLists.txt

and put the cmake_minimum_required before project. current cmake has removed support for < 3.5 and
tosses a warning if the project statement comes before the cmake_minimum_required statement.

bump minimum cmake version to 3.5

---

Apps/Common/Test/LR/TestMultiPatchLRRefine.C
src/ASM/LR/Test/TestASMu2D.C
src/ASM/LR/Test/TestASMu3D.C
src/LinAlg/LinAlgInit.C
src/LinAlg/PETScSupport.h

Avoid some deprecation warnings with newer versions of gtest/petsc.

Quell warnings with newer PETsc and gtest versions

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h
src/ASM/LR/ASMu3Drecovery.C

In particular avoid duplication by putting conditionals in base implementation.
Also add an option to disable use of bezier extraction in the 3DLR implementation. Bezier extraction from gauss points do not work with subgrid, so subgrid in 3D has always been broken. I will use that to fix subgrid but I want to do that afterwards as it requires downstream updates and I prefer to keep those in a separate PR - less branch jumping required.

ASMu3D(mx): simplify basis function cache

---

src/SIM/SIMinput.C

we need to instance the ProcessAdm and not pass a temporary. holding a reference to a temporary is not enough to keep it alive, which means it is killed and consequently the reader holds an invalid reference.

fixed: reading nodes from HDF5 file

---

src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Drecovery.C

we cannot uniformly use bezier extraction from gauss points
with subgrid, since we are not evaluating in gauss points
distributed across the element for all bases. this because
our integration elements have an additional subdivision,
which means the pressure basis is evaluated in non-uniform points
(ie we evaluate in 4 distinct sets of gauss-points over its elements).
Sits on top of https://github.com/OPM/IFEM/pull/619

ASMu3Dmx: disable bezier extraction with subgrid

---

src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h

- use getElementsAt
- no reason to have a vector of evaluation objects

cleanup ASMuxDmx::evalSolution

---

src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h

This exposes stride and offset for x vector in utl::vector<T>::add and adds an extractBlock method to utl::matrix<T>.
Useful for making code more readable while doing some of the piola stuff.

Some matrix utilities

---

src/ASM/ASMs2D.C
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2DmxLag.C
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3DmxLag.C
src/ASM/BasisFunctionVals.h
src/ASM/FiniteElement.C
src/ASM/FiniteElement.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3Dmx.C

this allows simplifying the MxFiniteElement::(Hessian|Jacobian) methods.
add a type alias and a helper class to make it convenient.

changed: use BasisFunctionValues also in boundary integrals

---

src/SIM/SIM1D.C
src/SIM/SIM2D.C
src/SIM/SIM3D.C

Cosmetic change, to avoid double print of the explicit knot definition. Hopefully without regression..

Changed: Remove "with grading" printout when explicit knots

---

src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs1DLag.C
src/ASM/ASMs1DLag.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DLag.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h
src/ASM/ASMs3Dmx.C
src/ASM/ASMsupel.C
src/ASM/ASMsupel.h
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h

This adds support for separate geometry in evalSolution(2) for struct ASMs.

ASMsxDmx::evalSolution: support separate geometry

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2DC1.C
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DLag.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h
src/ASM/ASMsupel.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/Test/TestASMs1D.C
src/ASM/Test/TestASMs2D.C
src/ASM/Test/TestASMs3D.C
src/SIM/SIMinput.C

That is the last commit, using the oneGroup() method. Hopefully this will remove the data race encountered now and then for the SSUprofil test.
The rest here is some cleaning/fixing of the `getBoundaryElms()` method, including implementation for Lagrange. Notice that this method now also is used when setting up the thread group for boundary integrals. Think it is equivalent to the code it replaces.

Deactivate multi-threading for patches with rigid coupling

---

src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h

- use language construct to manage pointers
- use anon namespace
- use override
- use type aliases, not typedefs
Sits on top of https://github.com/OPM/IFEM/pull/635

ExprFunctions: some modernization

---

src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Test/TestFunctions.C

The EvalFunction (and EvalMultiFunction) will be made a template over a scalar type to support auto-differentation.
One limitation of the c++ language is that you cannot partially specialize a member function, you can only fully specialize them. That implies that we would have to duplicate the specializations, one for Reals and one for the autodiff type. This is suboptimal. 
For this reason I have changed the approach to use a common implementation of the evaluate for Vec, Tensor and STensor expression functions.
One minor niggle with this is that we then end up exposing the internal column-major storage format for tensors, ie,
the input files have to specify the tensors in column major order ux|vx|uy|vy instead of the prior ux|uy|vx|vy. This is a little meh right now, but it is just a …

ExprFunction: use a common evaluate() implementation

---

src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h
src/Utility/Vec3.h

Firstly, a new `<grid>` tag within the `<resultpoints>` scope is added, to enable easy definition of result points in a grid pattern. Each result component (primary and secondary variables) is the saved to separate files, one column for each grid point (the physical time as the first column) and the time/load steps as rows. Then these files can be used as input to the python script for calculation of optimal sensor placement.

Added: Option to save result components on grid files

---

src/LinAlg/SparseMatrix.C
src/LinAlg/Test/TestSparseMatrix.C
src/SIM/NewmarkSIM.C
src/SIM/NonLinSIM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h

Instead of dumping them every iteration which is not that useful for Nonlinear/Newmark simulations.
But consider that as an option later, if/when needed.

Dump system matrices and RHS-vector in the start of each load/time step only

---

src/SIM/AdaptiveSetup.C

we have to use getNodes(1) to get the proper size. In general this resulted in the wrong number of functions being refined
for single basis methods and mixed methods projecting on the first basis. It also lead to crashes if 100% of function were to be refined since it selected too many functions / non-existing functions for refinement.

fixed: reset error array to appropriate size

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3Drecovery.C

We cannot use the MNPC directly if there are additional DOFs in the model.

ASMuxD::evalSolution(P): do not use MNPC directly if there are multipliers

---

src/SIM/Test/TestXMLInputBase.C
src/SIM/Test/with_include.xml
src/SIM/XMLInputBase.C

"Small" bug introduced when we moved to tinyxml2. After include was injected a closing tag was added for the currently processed element. This meant we got an early closing tag which broke the structure of the XML document.

Fix xml include files

---

Apps/Common/EqualOrderOperators.C

while technically this makes no difference, it is
better to be consistent

ResidualOps: flip sign of Divergence term

---

CMakeLists.txt
src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1DLag.C
src/ASM/ASMs2DLag.C
src/ASM/ASMs3D.C
src/ASM/ASMs3DLag.C
src/ASM/ASMu2DLag.C
src/ASM/ASMu2DLag.h
src/ASM/IntegrandBase.C
src/ASM/IntegrandBase.h
src/SIM/SIMbase.C

For use when reading rigid element definitions from external mesh file.
Also fixed a crash if MLGN is empty.
The support for 2D Lagrangian patches with a mix of 3- and 4-noded elements is also included here.
This is sufficient for the regression tests in OPM/IFEM-ShellEx to pass.

Added: ASMbase::addRigidCouplings()

---

src/ASM/ASMmxBase.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/LRSplineFields2Dmx.C
src/ASM/SplineFields2Dmx.C

Running staggered Boussinesq simulations with Piola mapped velocities we need to apply the forward Piola mapping when evaluating the velocity field in the temperature advection equation.
I'm not too thrilled about putting the flag in the ASM but I cannot see any cleaner way. At least it's sort of kept private, but the field and ASM both know the secret.

Coupling fields: Support Piola mapping

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMu2DLag.C
src/ASM/ASMu2DLag.h
src/LinAlg/SystemMatrix.C
src/LinAlg/SystemMatrix.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMinput.C
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h
src/Utility/ElementBlock.C
src/Utility/ElementBlock.h
src/Utility/VTF.C

When a Lagrange mesh consists of a mixture of quads and triangles (and possibly beams as well). The elements are written to the VTF-file block-wise, ordered by increasing number of element nodes. Thus, the element output order is different than the internal ordering of the elements in the patch and a permutation of the result arrays is needed. This will take care of it.
The `SIMoutput::writeGlvNo()` method is extended to also write out the global element numbers as element results - useful for debugging complex models.
Finally (last commit), the option to define explicit element sets as topological items is added for `ASMu2DLag`, similar as already available for `ASMu1DLag`.

Fix VTF output of element results for mixed Lagrange meshes

---

src/Utility/ExprFunctions.C
src/Utility/Functions.h

in particular this allows enabling auto-diff for functions parsed in applications

added: utility function for parsing an expression function

---

CMakeLists.txt
src/ASM/ASMLagBase.C
src/ASM/ASMLagBase.h
src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs1DLag.C
src/ASM/ASMs1DLag.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DLag.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h
src/ASM/ASMsupel.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/NewmarkMats.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

If we have a non-rectangular domain and want to output results in a 2D raster image.
(For optimal sensor placement calculations).
Also the option to dump the results in either all nodal points, or at all element centers.

Added: Option for Cartesian grid output

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ElmMats.C
src/ASM/HHTMats.C
src/ASM/NewmarkMats.C
src/LinAlg/SAM.C
src/SIM/NewmarkSIM.C
src/SIM/NonLinSIM.C
src/SIM/SIMbase.C

In case the external element numbers are truly external, and not just a generated sequence [1,nel], like when importing Nastran input files, we need to account for that when allocating the buffers.
Also use element matrix buffers when doing linear multi-load-case simulation using the NonLinSIM driver.

Element matrix cache fix

---

src/SIM/AdaptiveSetup.C
src/SIM/AdaptiveSetup.h

useful for staggered solvers where model number of DOFs is not the total number of DOFs

added: allow specifying number of current DOFs in AdaptiveSetup::calcRefinement

---

src/ASM/ASMbase.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMLRSpline.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Dmx.C

sharing VTF output between different ASMs, element orders
may differ. we need to order things in the VTF in the correct
output by using the correct gridParameters and MLGE.
for element norm outputs these have to externally been
reordered to the master patch order before being sent
to writeGlvN.
Also move the copyRefinement implementation to free functions to facility reuse in such staggered solvers.
I need to reuse these functions in adaptive staggered equal-order Boussinesq.

Fix VTF output for staggered solvers sharing VTF

---

src/ASM/ASMs1DLag.C
src/ASM/ASMs1DLag.h
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DLag.h
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h
src/LinAlg/DenseMatrix.C
src/LinAlg/DenseMatrix.h
src/LinAlg/DiagMatrix.C
src/LinAlg/ISTLMatrix.C
src/LinAlg/PETScMatrix.C
src/LinAlg/SAM.C
src/LinAlg/SPRMatrix.C
src/LinAlg/SPRMatrix.h
src/LinAlg/SparseMatrix.C
src/LinAlg/SystemMatrix.C
src/LinAlg/SystemMatrix.h
src/SIM/MultiStepSIM.h
src/SIM/SIMbase.C
src/SIM/SIMmodal.h
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

The first commit adds the possibility of evaluating the secondary solution at the center of each element for subsequent OSP calculations. The next two commits facilitate evaluation of nodal velocity and accelerations for OSP. This works under the assumption that if the array of solution vectors have 3 or more vectors, then the last two of them are the velocity and acceleration vectors, respectively.
The last two commits make it possible to detect that a system matrix has not received any contributions and then perform an early exit with a specific error message, instead of that standard factorization error which does not point to the actual problem, or even worse; continuing without solving assuming all is fine.

Pointwise velocity and acceleration output, element center output

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1D.h
src/ASM/ASMu2DLag.C
src/ASM/ASMu2DLag.h
src/ASM/FiniteElement.C
src/ASM/FiniteElement.h
src/SIM/SIMinput.C

Basically, adding nodal eccentricity vectors as member in class `FiniteElement`.
Also in this PR (totally unrelated, I know) is the option to specify an element set (for unstructured 2D Lagrange meshes) through one or more bounding boxes (third commit).

Small beam extensions

---

src/ASM/ASMbase.h
src/ASM/ASMsupel.C
src/ASM/ASMsupel.h
src/ASM/ASMu1DLag.C
src/ASM/ASMu1DLag.h
src/ASM/ASMu2DLag.C
src/ASM/ASMu2DLag.h
src/ASM/Test/TestMatlabPatch.C
src/LinAlg/SAM.C
src/LinAlg/SAM.h
src/SIM/SIMinput.C
src/SIM/SIMsupel.C

And similarly `getElementSet()` --> `parseElemSet()`.
The new methods also map from external node/elem numbers to local indices.
Added: `ASMu2DLag::addToNodeSet()`.

Changed: Replace non-const getNodeSet() methods by parseNodeSet().

---

Apps/Common/SIMExplicitRKE.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMu3D.C
src/LinAlg/MatVec.C
src/LinAlg/SparseMatrix.C
src/SIM/NewmarkSIM.C
src/SIM/SIMbase.C

these are not portable and causes warnings with newer compilers.
In particular VLAs is a C extension that just happens to be available in gcc and clang. However, never versions warns when they are used, so let's not.

avoid VLAs

---

src/ASM/ASMunstruct.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMLRSpline.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/GlobalNodes.C
src/ASM/LR/GlobalNodes.h
src/ASM/LR/Test/ASMuCube.h
src/ASM/LR/Test/ASMuSquare.h
src/ASM/LR/Test/TestGlobalNodes.C
src/SIM/AdaptiveSetup.C
src/SIM/SIMbase.C
src/SIM/SIMinput.C
src/SIM/SIMinput.h

Extracted from https://github.com/OPM/IFEM/pull/255
I left out the dd part since it's not yet working and not yet required.
It's time to get this in.

added: support for mixed multipatch adaptive simulations

---

src/ASM/ASMLagBase.C
src/ASM/ASMLagBase.h
src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1DLag.C
src/ASM/ASMs1DLag.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DLag.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h
src/ASM/ASMsupel.h
src/ASM/AlgEqSystem.C
src/ASM/AlgEqSystem.h
src/LinAlg/DenseMatrix.C
src/LinAlg/DiagMatrix.C
src/LinAlg/DiagMatrix.h
src/LinAlg/MatVec.C
src/LinAlg/SPRMatrix.C
src/LinAlg/SparseMatrix.C
src/LinAlg/SparseMatrix.h
src/LinAlg/SystemMatrix.h
src/LinAlg/Test/TestSPRMatrix.C
src/LinAlg/matrix.h
src/LinAlg/matrixnd.h
src/SIM/SIMoutput.C
src/Utility/Vec3.h

Added a virtual method `getElementCenter()` in `ASMbase` for calculation of geometric center of a specified element. Implemented for all Lagrange patches. In addition the LRSpline patches already had these implemented, but they are now also available via the `ASMbase` interface.
Also added methods to assign a list of currently active elements. This can be used to split the assembly stage into several sub-steps, in case some manipulation is desired in between the assembly of various element groups, for instance.
Also added missing newline in the matrix_market output format for system matrices.
Finally, a  consistent copy constructor and assignment operator are added for `AlgEqSystem`. This includes some fixes of the copy constructors for `SystemMatrix` sub-classes.

 Facilitate splitting the assembly step in two or more parts

---

3rdparty/autodiff/autodiff/reverse/var/var.hpp
src/LinAlg/matrix.h
src/Utility/HDF5Restart.C
src/Utility/HDF5Writer.C

While bumping to c++-20 won't happen before Ubuntu 26.04 (ie when 22.04 is out of support), I tried and it's mostly straight forward. One fix and one warning quell which are already valid under c++-17 so we may as well merge them now.
Also avoid some VLAs in HDF5Writer

C++20 fixes

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/LinAlg/SparseMatrix.h
src/SIM/SIMoutput.C

Was incorrect for multi-patch models, where we need to add an offset to the element index equal to the total number of elements in the previous patches when accessing the global array.

Fixed: Extraction of patch-level element results with internal ordering

---

src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMsupel.C
src/ASM/ASMsupel.h
src/ASM/ASMu1DLag.C
src/ASM/ASMu1DLag.h
src/ASM/ASMu2DLag.C
src/ASM/ASMu2DLag.h
src/ASM/ASMutils.C
src/ASM/IntegrandBase.C
src/Utility/Vec3.h

Of significance is that the `nodeSets` and `elemSets` containers are now protected (instead of private), such that they can be accessed by sub-classes, and the introduction of the bool second argument for `addTo[Node|Elem]` methods. The rest is cosmetics

Small changes regarding element/node sets for Lagrange patches

---

src/ASM/ReactionsOnly.C
src/ASM/ReactionsOnly.h
src/LinAlg/SAM.C
src/LinAlg/SAM.h
src/LinAlg/matrix.h
src/SIM/HHTSIM.C
src/SIM/HHTSIM.h
src/SIM/NewmarkNLSIM.h
src/SIM/SIM1D.C
src/SIM/SIM1D.h
src/SIM/SIM2D.C
src/SIM/SIM2D.h
src/SIM/SIM3D.C
src/SIM/SIM3D.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMgeneric.C
src/SIM/SIMgeneric.h

These are typically smaller-sized containers which does not require the algebra operations as typical NDOF-length vectors. A `utl::vector` copy constructor is added for easy conversion in the rare event we actually do want to do some algebra stuff. Also fixed a harmless memory leak in `HHTSIM` on destruction.
This used to be part of #729 but is taken out as a prelude for it, as it is a separate issue.

Use RealArray as type for reaction forces containers

---

Apps/Common/CompatibleOperators.C
Apps/Common/CompatibleOperators.h
Apps/Common/PiolaOperators.C
Apps/Common/PiolaOperators.h
Apps/Common/Test/TestCompatibleOperators.C

Instead take arguments passed by application.
This decouples the operators from Stokes logic, improving reusability (and sanity).

(Compatible|Piola)Operators: remove hardcoded indices 

---

src/ASM/ASMenums.h
src/ASM/IntegrandBase.h
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h
src/Utility/HDF5Writer.C

This can be used to filter out specific result components for output to VTF.
The suppressOutput() method needs to be overridden by a app-specific subclass, default is not filtering.

Added: virtual method IntegrandBase::suppressOutput()

---

src/ASM/ASMbase.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/BasisFunctionCache.C
src/ASM/BasisFunctionCache.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h

application may have to change this and this would create problems in basis function cache since it is sized according to number of max threads. this adds a callback so application can signal and have the buffers resize accordingly

added: callback for changing number of threads

---

src/ASM/ASMs2DLag.C
src/ASM/ASMs3DLag.C

the latter includes GLMs. causes missing output in VTF files

fixed: use getNoProjectionNodes() instead of getNodes()

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs2D.C
src/ASM/LR/ASMu2D.C
src/LinAlg/Test/MatrixTests.h
src/LinAlg/Test/TestMatVec.C
src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h

The `n` argument to the `[sd]axpy` calls was too large resulting in invalid memory access.
Also adding some sanity checking on the stride arguments, they can be negative (at least for BLAS version), but not zero.
Also adding an overloaded `utl::matrix::fill()` method.

Fixed: BLAS version of utl::vector::add with stride larger than 1

---

src/ASM/HHTMats.C
src/ASM/IntegrandBase.h
src/ASM/NewmarkMats.C
src/ASM/NewmarkMats.h
src/SIM/EigenModeSIM.C
src/SIM/EigenModeSIM.h
src/SIM/GenAlphaSIM.C
src/SIM/GenAlphaSIM.h
src/SIM/HHTSIM.C
src/SIM/HHTSIM.h
src/SIM/MultiStepSIM.C
src/SIM/MultiStepSIM.h
src/SIM/NewmarkNLSIM.C
src/SIM/NewmarkNLSIM.h
src/SIM/NewmarkSIM.C
src/SIM/NewmarkSIM.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMsolution.C
src/SIM/SIMsolution.h
src/SIM/Test/TestNewmark.C
src/SIM/Test/TestNonLinSIM.C
src/SIM/Test/TestSolution.C

This is to facilitate accessing the solution state of the previous time step(s) on element/integration point level. The new order is u0,v0,a0, u1,v1,a1, u2,v2,a2, ... while before it was u0,u1,u2,...,v0,a0 and the previous velocity and acceleration states where not available.

Reorder solution vectors in Newmark drivers

---

src/ASM/Integrand.h
src/ASM/IntegrandBase.h
src/Utility/ExprFunctions.h
src/Utility/Function.h

Then we don't need the setParameter() wrapper in the Function class but can override directly.

Changed: Use std::string as type on the first argument for the virtual setParam() method

---

src/SIM/EigenModeSIM.C
src/SIM/MultiStepSIM.C
src/SIM/MultiStepSIM.h
src/SIM/NewmarkSIM.C
src/SIM/NonLinSIM.C

Added the option:
<eigenmodes>
<modes scale="1.23">1 2 3 5 7 8</modes>
</eigenmodes>
which is more compact than specifying mode by mode using `<mode number="1">1.23</mode>`.
The latter syntax is still valid though.

More flexible specification of modes for EigenModeSIM

---

src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs2DTri.C
src/ASM/ASMu1DLag.C
src/ASM/ASMu2DLag.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoutput.C
src/Utility/Functions.C
src/Utility/VTF.C

The first commit is unrelated - an extension of the `Parametric` function class defining element activation histories.
The second commit assigns external element numbers to `ElementBlock` objects, for unstructured Lagrange patches (this was erroneously left out initially).
Then, in the third commit the `SIMoutput::writeGlvNo()` method is extended to also output the original external element numbers as a scalar field to `VTF`. This is needed when the external numbers do not consist of a monotonic sequence 1...nel, but contains "holes". The elements are then renumbered such that they can be used as indices in global element arrays. Therefore we need to do this in order to visualize the original numbers.
The last two commits are also unrelated: Signature change for virtual method …

VTF output of external element numbers

---

src/ASM/ASMs2DLag.C
src/ASM/GlbL2projector.h
src/ASM/Integrand.h
src/ASM/IntegrandBase.h
src/LinAlg/SPRMatrix.C
src/SIM/NewmarkSIM.C

To avoid that the system Newton matrix is assembled unnecessarily when iterating the RHS vector only.
This will require some downstream updates though (for users of the NewmarkSIM driver).

Changed: Use SIM::RHS_ONLY also in NewmarkSIM

---

src/Utility/Profiler.C
src/Utility/Profiler.h

Output to the per-process output instead of std::cout.
In particular this fixes unstable regression tests in parallel, where the profiler output from all processes has the potential to end up interleaved with output we are actually checking for (e.g. recently introduced eigenvalue regression tests).

Profiler: output to IFEM::cout

---

src/Utility/Test/TestThreadGroups.C
src/Utility/ThreadGroups.C
src/Utility/ThreadGroups.h

this adds the specified elements in one stripe,
so they can all be safely assembled in parallel
in structured asms.
to be used for threadsafe integrand handling

ThreadGroups: add oneStripe(list)

---

src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs1DLag.C
src/ASM/ASMs1DLag.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DLag.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMLRSpline.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/Test/TestASMu2D.C
src/ASM/LR/Test/TestASMu3D.C
src/ASM/Test/TestASMs1D.C
src/ASM/Test/TestASMs2D.C
src/ASM/Test/TestASMs3D.C

This should replace #768.
The main difference is that the class-dependent implementation is now in the static method `createMNPC()` for each class, which then is used by the the virtual `getElmNodes()` methods. The static methods are also used internally instead of going via the virtual method. In addition, the Lagrange implementation of `getElmNodes()` was probably buggy, in that the `nx`, `ny` and `nz` members where used also when calculating for the projection basis. Now they are recalculated using the correct spline object before invoking the static method for generating  the MNPC.

Refactor MNPC generation for reuse

---

src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs2D.h
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DLag.h
src/ASM/ASMs2Drecovery.C
src/ASM/ASMs3D.h
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h
src/ASM/ASMs3Drecovery.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Drecovery.C
src/LinAlg/DenseMatrix.C
src/LinAlg/DenseMatrix.h
src/LinAlg/DiagMatrix.C
src/LinAlg/DiagMatrix.h
src/LinAlg/SPRMatrix.C
src/LinAlg/SPRMatrix.h
src/LinAlg/SparseMatrix.C
src/LinAlg/SparseMatrix.h
src/LinAlg/SystemMatrix.C
src/LinAlg/SystemMatrix.h

So that we can override this for other matrix types (e.g. PETSc) in the future.

L2 projection: Add interface for assembling

---

src/ASM/ASMs1DLag.C
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DTri.C
src/ASM/ASMs2Dmx.C
src/ASM/ASMs3DLag.C
src/ASM/ASMs3Dmx.C
src/ASM/LR/ASMLRSpline.C
src/SIM/SIMoutput.C

This fixes #783. We now always consider basis 1 only when writing BC codes to VTF-file, such that the extraordinary nodes (either from rigid elements or contact analysis) are excluded. If not, the export would fail for Lagrange meshes where a one-to-one correspondence between the FE nodes and the visualization nodes are assumed. For spline meshes it worked since the fields are interpolated anyway.
Also deactivating multi-threading for Lagrange and mixed models when requested. It was only done for single-basis spline models so far.

Fix VTF output for Lagrange models with extra-ordinary nodes

---

src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h
src/SIM/SIMadmin.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMmultiCpl.C
src/SIM/SIMmultiCpl.h
src/Utility/Functions.C

Bug introduced in commit d7780614f43dad0cee714838a6933b2ee1cf677e.
type="linear" should result in a function linear in time and constant in space, but ended up with constant in time also.

Fixed: utl::parseTracFunc() for type="linear"

---

src/Eig/EigSolver.C
src/SIM/SIMoptions.C

Running with `-eig 4 verbose` will now print a message for each Arnoldi iteration (A*x and solve).
Also separate timers for the two operations.

Added: Arnoldi iteration verbose print and profiling

---

src/Eig/EigSolver.C
src/LinAlg/SparseMatrix.C
src/LinAlg/SparseMatrix.h
src/LinAlg/SystemMatrix.h

Implemented for SparseMatrix only.
Use this in eig::solver() to speed up the matrix-vector multiplication in case of single-thread.

Added: virtual method SystemMatrix::compressPattern()

---

src/ASM/ASMs2DLag.C
src/ASM/ASMs3DLag.C

as BsplineBasis::knotInterval() is not thread safe. this is called when evaluating the integrand solution inside the omp loop.

fixed: parallel L2 assembly for ASMsxDLag

---

src/ASM/AlgEqSystem.C
src/SIM/MultiStepSIM.C
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

The protected member `addDisBlk` is added to class `SIMoutput`, through which downstream apps may specify additional displacement field blocks - not belonging to the FE model itself - to be written to the VTF file. handy for visualization of sea surface elevation, etc.
Extended the virtual `writeGlvA()` method with the time argument.
Also (second commit) adding profiling of the `SystemMatrix::initAssembly()` call.

Additional app-dependent displacement blocks

---

src/LinAlg/PETScMatrix.C
src/LinAlg/PETScMatrix.h

For allowing MLC shell simulator to use PETSc

PETSc: implement ::add() and fix reuse of matrices

---

src/ASM/IBGeometries.C
src/ASM/IBGeometries.h
src/SIM/MultiStepSIM.h
src/SIM/NewmarkSIM.h
src/SIM/SIM2D.C
src/SIM/SIM2D.h
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h
src/Utility/Test/TestTensor.C
src/Utility/VTF.C
src/Utility/VTF.h

If an expression function is registered for additional VTF output, this will ensure that state dependency is accounted for,
such that "ux", "uy", and "uz" is evaluated correctly as solution variables.

State dependency for additional functions
