OPM/IFEM

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2Drecovery.C
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3Drecovery.C
src/LinAlg/SAM.C
src/SIM/InitialConditionHandler.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Functions.C
src/Utility/SplineUtils.C
src/Utility/SplineUtils.h

Utility that will be used for projecting a phase field function onto the basis for the FractureDynamics application. Not yet finished. Need a SIMbase method on top of this.
I though we had something like this before, but could not find it. Therefore this.

Function projection

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2Drecovery.C
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3Drecovery.C
src/ASM/BlockElmMats.C
src/ASM/BlockElmMats.h
src/ASM/Test/TestBlockElmMats.C
src/LinAlg/SAM.C
src/SIM/InitialConditionHandler.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Functions.C
src/Utility/SplineUtils.C
src/Utility/SplineUtils.h

Used for multi-integrand problems with monolithic coupling.
NB: Not tested yet, so this is very WIP.

Added: New class for block element matrices. WIP

---

src/LinAlg/SAM.C
src/LinAlg/SAM.h
src/LinAlg/matrix.h
src/SIM/NonLinSIM.C
src/SIM/NonLinSIM.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h

Noen valgrind issues + maxIncr som input-variabel i NonLinSIM

Matrix extension

---

Apps/Common/MultiPatchModelGenerator.C
Apps/Common/MultiPatchModelGenerator.h
Apps/Common/SIMMultiPatchModelGen.h
src/ASM/DomainDecomposition.C
src/SIM/ModelGenerator.C
src/SIM/ModelGenerator.h
src/SIM/Test/TestSIM.C

Se på dette. Syns bare det var litt merkelig med en virtuell metode som har identisk implementasjon i alle underklassene. Dessuten kan jeg ikke bruke override enda samt diverse stl-initialisringer, så lenge jeg bruker gcc 4.6 for debugging. Resten er kosmetisk.

Model generator tidying

---

Apps/Common/SIMNodalConstraint.C
Apps/Common/Test/TestSIMNodalConstraint.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/Test/TestASMu2D.C

- corners was not properly constrained in ASMu2D with non-projected b.c's
- open edges were broken

Some fixes for ASMu2D and boundary conditions

---

Apps/Common/SIMSolverAdap.h
src/ASM/LR/ASMu2Drecovery.C

- fix order of solution vector registry in SIMSolverAdap
- use a sparse system for the interpolation problem in ASMu2D. problem is sparse and large.

Fix two LR issues

---

src/ASM/ASMunstruct.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Drecovery.C

This is a remake of PR #52 which had to be taken down for reasons described there.

3D LR projection and bezier evaluation

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu2Dmxrecovery.C
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3Drecovery.C

Please don't make this PR linger because it *will* create conflicts if you make alterations to any of the LR-files without it.

Cosmetics: proper whitespace use in src/ASM/LR

---

Apps/Common/EqualOrderOperators.h

changed: unify (EqualOrder|Compatible)Operators::Residual::Laplacian

---

src/LinAlg/matrix.h

alpha, beta, strides and offsets

added: utl:matrix::multiply() exposing the full gemv API

---

src/LinAlg/matrix.h

Not a lot BLAS can do better, but it can possibly achieve slightly better cache utilization through smarter traversals.

added: use BLAS in outer_product

---

Apps/Common/CompatibleOperators.C
Apps/Common/CompatibleOperators.h
Apps/Common/EqualOrderOperators.C
Apps/Common/EqualOrderOperators.h

add skew-symmetric form of convection to weak operators.

Skew-symmetric convection

---

src/ASM/ASMs3Dmx.C
src/LinAlg/PETScMatrix.C

- Fix sanity check/ hack fix in parallel domain decomposition
- Fix 3D mixed ASM for uneven amount of elements in each direction

Some small fixes

---

.gitignore

More of a suggestion than anything else, what do people think?

add: cleanup status, ignore common apps/build folders

---

src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

Added: Utility method SIMbase::getReactionForces.
Use this in the apps instead of myEqSys->getReactions().

Added: Print analytic solution at the result points, when available

---

src/ASM/AlgEqSystem.C
src/ASM/AlgEqSystem.h
src/ASM/ElmMats.C
src/ASM/ElmMats.h
src/ASM/IntegrandBase.C
src/SIM/AdaptiveSIM.C
src/SIM/EigenModeSIM.C
src/SIM/MultiStepSIM.C
src/SIM/MultiStepSIM.h
src/SIM/NonLinSIM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h

Added: Debug print of extracted element solution vectors.
Changed: Default value of argument witRF in SIMbase::initSystem to false.
Changed: Removed three spaces in the summary print for scalar solutions.
No merge yet, companion to the staggered branch for OpenFrac

Added: Assembly of scalar quantities together with the equation system.

---

Apps/Common/MultiPatchModelGenerator.C
Apps/Common/Test/TestMultiPatchModelGenerator.C

these contain the patches touching the relevant boundary
and those not touching any boundary respectively.

added: generate [Edge|Face]xPatches and InnerPatches topology sets

---

src/ASM/ASM2D.C
src/ASM/ASMenums.h
src/ASM/IntegrandBase.C
src/SIM/SIM2D.C
src/SIM/SIMoptions.C

On request, here (the second commit) is a solution to #122.
The first commit is just a cosmetic thing (I think).

Improved support for triangles

---

src/ASM/ASMunstruct.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/Utility/ThreadGroups.h

Mesh is split in a minimum number of colors. Each member in a given color can be processed in parallel on multiple threads.

add multithreaded lr assembly

---

Apps/Common/SIMSolver.h
src/ASM/AlgEqSystem.C

Useful when debugging sensitive models.

Added: Option to store also the diverged solution on VTF before exiting

---

Apps/Common/SIMCoupled.h
Apps/Common/SIMOverride.h
Apps/Common/Test/TestSIMCoupled.C
Apps/Common/Test/TestSIMOverride.C
src/ASM/Field.C
src/ASM/Field.h
src/ASM/Fields.C
src/ASM/LagrangeField2D.C
src/ASM/LagrangeField2D.h
src/ASM/LagrangeField3D.C
src/ASM/LagrangeField3D.h
src/ASM/SplineField2D.C
src/ASM/SplineField2D.h
src/ASM/SplineField3D.C
src/ASM/SplineField3D.h
src/ASM/SplineFields2D.C
src/ASM/SplineFields2Dmx.C
src/ASM/SplineFields2Dmx.h
src/ASM/SplineFields3D.C
src/ASM/SplineFields3Dmx.C
src/ASM/SplineFields3Dmx.h
src/ASM/Test/TestSplineField.C
src/ASM/Test/TestSplineFields.C
src/SIM/SIMdependency.C
src/SIM/SIMdependency.h

- some cosmetic fixes
- add tests for splinefields
- fix multithreading issues in field classes
- add support for instancing a field(s) over a solution vector with other bases / components. extract requested bit
- add support for mixed-basis vector fields for usage with div-compatible discretizations

Revamp fields support

---

src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h

I have a temporary hack I'm using, but distilled this matrix3d functionality from it that might be useful to pull into master.

functionality in utl:matrix3d

---

src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h

- avoid copying a matrix
- fix global integration point counter

Some small fixes in 3D LR ASM

---

src/SIM/SIMoptions.C
src/SIM/SIMoptions.h

needs to be utilized in the applications

added: input option for enabling/disabling element norm output

---

src/Utility/AnaSol.C
src/Utility/AnaSol.h

necessary for e.g. boussinesq where you have a velocity,
a pressure and a temperature field.

added: support any number of scalar solutions in anasol

---

Apps/Common/CompatibleOperators.C
Apps/Common/EqualOrderOperators.C
Apps/Common/EqualOrderOperators.h
Apps/Common/Test/TestCompatibleOperators.C

This adds some new weak/residual ops used in the coupled Boussinesq implementation.

Preparation for coupled Boussinesq

---

Apps/Common/SIMCoupled.h
Apps/Common/SIMCoupledSI.h
Apps/Common/SIMSemi3D.h
Apps/Common/SIMSolverTS.h

fixup wrong signature in SIMSemi3D

---

src/ASM/LR/ASMu2Dmxrecovery.C

Fix CGL2 projection for ASMu2Dmx

---

src/ASM/ASMs2DC1.C
src/LinAlg/matrix.h
src/SIM/SIMoutput.C
src/Utility/VTF.C

Se om dette tar knekken på den clang-støyen du nevnte. Hvis det er flere lignende saker (som jeg ikke ser selv), er det greit få med med de også her før merging.

Fixed: Some minor issues pointed out by clang

---

src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Drecovery.C

a bit copy-pasty but so is the 2d code i copy-pasted ;)

added: L2-projected non-homogenous dirichlet boundary conditions for LR-b splines

---

src/ASM/ASM3D.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h
src/ASM/LR/ASMu3Drecovery.C
src/SIM/SIMoptions.C

Some work left, but opening early to share work.
It appears to work fine (with obvious restrictions). However, the lack of support for non-homogeneous dirichlet conditions in ASMu3D bites us hard to the testing front.

initial support for mixed 3D LR assembly

---

src/ASM/Field.C
src/ASM/Fields.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/LRSplineField2D.C
src/ASM/LR/LRSplineField2D.h
src/ASM/LR/LRSplineField3D.C
src/ASM/LR/LRSplineField3D.h
src/ASM/LR/LRSplineFields2D.C
src/ASM/LR/LRSplineFields2D.h
src/ASM/LR/LRSplineFields2Dmx.C
src/ASM/LR/LRSplineFields2Dmx.h
src/ASM/LR/LRSplineFields3D.C
src/ASM/LR/LRSplineFields3D.h
src/ASM/LR/LRSplineFields3Dmx.C
src/ASM/LR/LRSplineFields3Dmx.h
src/ASM/LR/Test/TestLRSplineField.C
src/ASM/LR/Test/TestLRSplineFields.C

this adds LR field classes so we can do staggered/semiimplicit simulations with mixed + LR.
depends on https://github.com/OPM/IFEM/pull/66 and to some extent on https://github.com/OPM/IFEM/pull/126

add LR field classes

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3Drecovery.C
src/ASM/LR/LRSplineFields2Dmx.C
src/ASM/LR/LRSplineFields3Dmx.C

also unify ASMu3D and ASMu2D code a little. note the first
also requires an updated libLRSpline

fix ASMu3D::evalSolution and ASMu3D::updateDirichlet for multi-patch

---

src/ASM/LR/ASMu2Dmx.C

respect &lt;store_eps_mesh/&gt; for mixed

add storemesh with mixed

---

src/ASM/ASMs2Dmx.h
src/ASM/ASMs2Drecovery.C

add global L2 projection for mixed 2D tensor splines

---

src/ASM/ASM2D.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/SIM/SIM2D.C
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

to facilitate comparison with Matlab solvers. So far only 2D linear quads.
The other commit is something else, an option scaling of the parameter domain when specifying non-uniform knots.

Dump of FE model to Matlab format

---

src/ASM/LR/ASMu3D.C

Faster, and works around issues in the computeBasis method for some models.
@VikingScientist

changed: use bezier extraction in evaluation of secondary solution.

---

src/ASM/ASMu2DLag.C
src/ASM/ASMu2DLag.h
src/ASM/Test/TestMatlabPatch.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMinput.C
src/SIM/SIMinput.h
src/Utility/Utilities.C
src/Utility/Utilities.h

Convenient if you want to compare a time history in IFEM with a matlab implementation

Added: Dump of solution matrix/vectors of several steps to the same file

---

src/LinAlg/PETScSolParams.C

fixed: allow setting ilu_fill_level for non-AMG driven ilu pcs

---

src/LinAlg/SparseMatrix.C
src/LinAlg/SparseMatrix.h

No idea why I thought this wasn't doable. Need more glasses!

added: reuse of symbolic factorization for umfpack solver

---

src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h

also avoid leaks on parsing failure

fixed: add some more segfault protection

---

src/ASM/ASMs2D.C
src/ASM/ASMs3D.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3D.C
src/SIM/SIMadmin.C
src/SIM/SIMadmin.h
src/SIM/SIMbase.C
src/SIM/SIMinput.C
src/SIM/SIMoutput.C

To facilitate suppression of threading group info and VTF output which can be substatial for big multi-patch models. But it is still nice to be able to get such output without compiling debug

Option to specify msgLevel on the input file

---

src/ASM/LR/ASMu3Dmx.C

implement ASMu3Dmx::evalSolution

---

src/ASM/AlgEqSystem.C
src/ASM/AlgEqSystem.h
src/ASM/IntegrandBase.C
src/ASM/IntegrandBase.h
src/SIM/AdaptiveSIM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMinput.C
src/Utility/FieldFunctions.C
src/Utility/FieldFunctions.h
src/Utility/HDF5Writer.C

OPM/IFEM-Elasticity#39 depends on this one. Apart from that, nothing here should be controversial.

Minor issues to clear the ground for dual fields and reaction force calculation for static linear elasticity

---

Apps/Common/SIMCoupled.h
Apps/Common/SIMCoupledSI.h
Apps/Common/SIMSolverTS.h
CMakeLists.txt
src/ASM/ASMbase.h
src/ASM/ASMunstruct.C
src/ASM/ASMunstruct.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/SIM/SIMinput.C
src/SIM/SIMinput.h
src/SIM/SIMoutput.C
src/SIM/TimeStep.h

This as an alternative to your NN_transfer branch and it should be equivalent.
My current adaptive OpenFrac simulation uses this.
Note includes OPM/IFEM#219 also which needs to be merged first.

Adaptive stuff

---

src/ASM/ASMunstruct.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h
src/SIM/AdaptiveSIM.C

need to remap to elements, not basis functions

fixed: truebeta refinement was broken

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Dmx.C

this was missing for no good reason.

added: G_MATRIX support to ASMu2D(mx)

---

src/SIM/SIMoutput.C

we have nearly 40 norms in boussinesq..

changed: get rid of the hardcoded maximum number of norms

---

src/ASM/ASMs2Drecovery.C
src/ASM/ASMs3Drecovery.C
src/ASM/LR/ASMu2Dmxrecovery.C
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3Drecovery.C

- assemble to a dense element matrix
- use outer_product for mass matrix calculation
mixed 2D LR is omitted as i have mostly completely rewritten the method in other work. it will get the same treatment then.

changed: optimize assembleL2Matrices

---

src/ASM/GlbNorm.h
src/SIM/SIMoutput.C

Triviality. Just tired of the long output of the result lines after each mesh refinement..

Changed: Suppress result point output for big groups (lines)

---

src/Utility/Test/TestGaussQuadrature.C

It seems I do not understand the triangle quadrature

added: unit tests for gaussian quadratures

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu3D.C
src/Utility/DataExporter.C

You did not give me a chance to comment on #243 before it was merged, as I did not check sintef-email yesterday. Therefore a new PR here with some amendments. Also check if the same time thief is hidden elsewhere.

Profiling of DataExporter::dumpTimeLevel + 3D fix

---

src/Utility/LagrangeInterpolator.C
src/Utility/LagrangeInterpolator.h
src/Utility/Legendre.C
src/Utility/Legendre.h
src/Utility/Test/TestLegendre.C

Doxy issues and don't use utl::vector when not needed

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/Test/TestASMu2D.C

As pointed out in #250 this was unimplemented.

added: store continuity of mesh line intersections in ASMu2D

---

Apps/CMakeLists.txt
jenkins/build-ifem-module.sh
src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs2D.C
src/ASM/Integrand.h
src/ASM/IntegrandBase.h
src/ASM/LR/ASMu2D.C
src/ASM/SAMpatch.C
src/LinAlg/SAM.C
src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h
src/Utility/MPC.h
src/Utility/Vec3Oper.C
src/Utility/Vec3Oper.h

This adds stuff needed when doing nonlinear Kirchhoff-Love shells.

Nonlinear shell support

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMstruct.C
src/ASM/ASMstruct.h
src/ASM/Integrand.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/Test/TestMatlabPatch.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMgeneric.C
src/SIM/SIMgeneric.h
src/SIM/SIMoutput.C

Currently for 2D LR-splines only (and non-mixed).
Not sure if this is the ideal solution, but at least it seem to work.

Framework for integration of consistent load vector due to point loads

---

src/ASM/ASMmxBase.C

whoopsie is obvious, but i still want a jenkins sanity check before commit..

fixed: we need to evaluate nb[b] before incrementing b

---

src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h

mark elements/functions which contributes beta% to the total error

added: support for the dörfel marking strategy

---

Apps/Common/SIMSolver.h
Apps/Common/SIMSolverAdap.h
src/ASM/ASMs2D.h
src/ASM/ASMs3D.h
src/ASM/DomainDecomposition.h
src/ASM/ElmMats.h
src/ASM/IntegrandBase.C
src/LinAlg/Test/MPI/TestISTLMatrix.C
src/LinAlg/matrix.h
src/SIM/SIMinput.C
src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Function.h
src/Utility/Profiler.h
src/Utility/ThreadGroups.h

- explicit constructors
- clarify operator precedence
- catch polymorphic exceptions by reference

Some static analyzer warning suppression

---

src/ASM/ASMs2D.C
src/ASM/ASMs3D.C
src/ASM/GlbNorm.C
src/ASM/GlbNorm.h
src/ASM/GlobalIntegral.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu3D.C
src/SIM/SIMbase.C
src/Utility/ThreadGroups.C
src/Utility/ThreadGroups.h

This fixes #280 
Still need for the mixed class, and maybe also tensor splines?

Efficient norm integration for LR

---

Apps/Common/SIMSolverAdap.h
src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h

in particular, this allows adaptivity for stationary, nonlinear systems
such as NavierStokes or Boussinesq.

added: add support for adaptive simulators using the ISolver interface

---

Apps/Common/SIMSolverAdap.h
src/ASM/HHTMats.C
src/ASM/HHTMats.h
src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h
src/SIM/EigenModeSIM.C
src/SIM/GenAlphaSIM.C
src/SIM/HHTSIM.C
src/SIM/HHTSIM.h
src/SIM/MultiStepSIM.C
src/SIM/MultiStepSIM.h
src/SIM/NewmarkNLSIM.C
src/SIM/NewmarkNLSIM.h
src/SIM/NonLinSIM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h
src/SIM/SIMsolution.C
src/SIM/SIMsolution.h
src/SIM/TimeStep.C
src/SIM/TimeStep.h

The main thing is the introduction of the SIMsolution class, which now holds the solution vectors to be stored on file in case of restart. Apps needing restart support then inherit this class to get the serialization feature. This is also used in the nonlinear/dynamic solution drivers.

New class SIMsolution for better serialization/restart support

---

src/SIM/NewmarkSIM.C

This adds an option for `<printCond />` in NewmarkSIM with the same implementation that currently exists in NonlinSIM.

Support output of condition numbers in newmark solver

---

src/Utility/Tensor.C
src/Utility/Test/TestTensor.C

The assignment operator fix in #291 created a valgrind issue.
This will hopefully resolve the matter.

Fixed: 2D to 3D Tensor assignment

---

Apps/HDF5toVTx/HDF5toVTx.C

fixed: remove unused LR flag

---

src/ASM/ASMs1D.C

Requires an updated GoTools, will trigger build once packages are in place.

added: second derivatives for rational curves

---

Apps/Common/SIMSemi3D.h
Apps/Common/SIMSolver.h
src/SIM/SIMinput.C
src/Utility/DataExporter.C
src/Utility/DataExporter.h
src/Utility/FieldFunctions.C
src/Utility/FieldFunctions.h
src/Utility/HDF5Base.C
src/Utility/HDF5Base.h
src/Utility/HDF5Reader.C
src/Utility/HDF5Reader.h
src/Utility/HDF5Restart.C
src/Utility/HDF5Restart.h
src/Utility/HDF5Writer.C
src/Utility/HDF5Writer.h

- HDF5Writer writes results
- HDF5Reader reads
- HDF5Restart reads and writes restart data

changed: split HDF5 class in 3 parts

---

Apps/Common/CompatibleOperators.C

use add and outer_product instead of hand-rolled loops

changed: simplify some CompatibleOperators

---

src/SIM/AdaptiveSIM.C
src/Utility/HDF5Restart.C

not number of projection nodes

fixed: vector should be sized as number of refine nodes

---

jenkins/build-ifem-module.sh

these are modules which are cloned, but not built

jenkins: add support for sidestreams

---

src/ASM/LR/ASMu2Dnurbs.C
src/ASM/SAMpatch.C
src/SIM/SIMbase.C
src/SIM/SIMinput.C
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

This fixes some issues when running with ignored patches in a big multi-patch model (a debugging tool).
Also, there was an index error when writing projected results to VTF such that they we incorrect for multi-patch models.

Some multipatch issues

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3Drecovery.C

Replaces #342 which was slightly incorrect and incomplete.
Instead of detailed comments on that one, I open a new PR instead.
This also includes for 2D LR which the IGA students run into this issue for last week.

Added: Default Gauss point selection for LRSplines

---

src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

Useful for inspection purposes

added: support output of explicit function to VTF

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/DomainDecomposition.C
src/ASM/DomainDecomposition.h
src/ASM/DualField.C
src/ASM/DualField.h
src/ASM/GlbL2projector.C
src/ASM/GlbL2projector.h
src/ASM/IntegrandBase.C
src/ASM/IntegrandBase.h
src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h
src/SIM/AdaptiveSetup.C
src/SIM/AdaptiveSetup.h
src/SIM/FunctionSum.C
src/SIM/FunctionSum.h
src/SIM/SIMargsBase.C
src/SIM/SIMargsBase.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMinput.C
src/SIM/SIMinput.h
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h
src/Utility/ElementBlock.C
src/Utility/ElementBlock.h
src/Utility/FieldFunctions.C
src/Utility/FieldFunctions.h
src/Utility/Function.h
src/Utility/TensorFunction.h

This contains some framework for doing so-called variational consistent postprocessing, where an explicit extraction function (dual solution field) is used to calculate sectional forces.

Variational consistent postprocessing

---

src/SIM/SIMinput.C
src/SIM/SIMoptions.C
src/SIM/SIMoutput.C

Mostly to be aligned with the wiki documentation, which I updated earlier this summer.

Small changes regarding input file parsing

---

Apps/Common/SIMExplicitRK.h

for controlling output to terminal

added: standalone setting in SIMExplicitRK

---

cmake/Scripts/IFEMTesting.cmake
src/Eig/Test/TestEigSolver.C

Not finished yet (arpack mode 5 and 6).

add test for eigen solvers

---

CMakeLists.txt
src/ASM/GlobalIntegral.h
src/ASM/ReactionsOnly.C
src/ASM/ReactionsOnly.h
src/LinAlg/SAM.C
src/LinAlg/SAM.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h

Some confusion on the 0.5 scaling factor. Now I think it is correct. Needed by OPM/IFEM-Elasticity#39
Also cleaned away some unused items in SAM, probably some leftover after PETSc refactor?

Reaction force norm fix

---

src/ASM/ASMs1D.C
src/ASM/ASMs2D.C
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs3D.C
src/SIM/SIMbase.C

use of an additional MADOF is required

changes needed for basic mixed FSI

---

Apps/Common/SIMImplicitLMM.h
Apps/Common/TimeIntUtils.C
Apps/Common/TimeIntUtils.h
src/SIM/NonLinSIM.C
src/SIM/NonLinSIM.h

This adds support for implicit LMM time stepping for SIM classes.

Add support for implicit linear multistep methods

---

src/ASM/NewmarkMats.C
src/ASM/NewmarkMats.h
src/LinAlg/DenseMatrix.C
src/LinAlg/DenseMatrix.h
src/LinAlg/DiagMatrix.C
src/LinAlg/DiagMatrix.h
src/LinAlg/SAM.h
src/LinAlg/SPRMatrix.C
src/LinAlg/SPRMatrix.h
src/LinAlg/SparseMatrix.C
src/LinAlg/SparseMatrix.h
src/LinAlg/SystemMatrix.C
src/LinAlg/SystemMatrix.h
src/LinAlg/Test/TestDiagMatrix.C
src/SIM/MultiStepSIM.C
src/SIM/MultiStepSIM.h
src/SIM/NewmarkSIM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMmodal.C
src/SIM/SIMmodal.h
src/SIM/SIMoutput.C
src/SIM/SIMoutput.h
src/Utility/ElementBlock.C
src/Utility/ElementBlock.h

The first two commits are more of cosmetic character.
Then a new system matrix class for diagonal systems is added.
which is used to facilitate the assembly of modal systems.

Support for modal time integration

---

src/ASM/LR/ASMu2Drecovery.C

fixed: use proper basis for evaluation in regularInterpolation

---

Apps/Common/Test/MPI/TestMultiPatchModelGenerator.C
src/ASM/ElmMats.C
src/ASM/HHTMats.C
src/ASM/IntegrandBase.h
src/ASM/NewmarkMats.C
src/ASM/Test/MPI/TestDomainDecomposition.C
src/ASM/Test/TestDomainDecomposition.C
src/LinAlg/SAM.C
src/LinAlg/Test/MPI/TestISTLMatrix.C
src/LinAlg/Test/MPI/TestPETScMatrix.C
src/LinAlg/Test/TestISTLMatrix.C
src/LinAlg/Test/TestPETScMatrix.C
src/LinAlg/readIntVec.h
src/SIM/AdaptiveSIM.C
src/SIM/HHTSIM.h
src/SIM/NonLinSIM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/Test/TestNewmark.C
src/SIM/Test/TestNonLinSIM.C
src/SIM/Test/TestSIM.C

Adding some basic tests involving structural damping.

More Newmark unit testing

---

src/LinAlg/ISTLSolParams.h
src/LinAlg/PETScMatrix.h

fix compiling of parallel ISTL unit tests

---

src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h

changed: move copying of refinement to separate method

---

Apps/Common/SIMSolverAdap.h

I had to give up on beating AdaptiveSIM into doing what I want it to when doing a staggered adaptive simulator. Thus, I added a solver template where the adaptive parts are handled internally in the simulator.

added: solver template for simulators with internal adaptation

---

Apps/Common/CMakeLists.txt
Apps/Common/Test/LR/TestMultiPatchLRRefine.C
src/LinAlg/PETScMatrix.C
src/SIM/SIMinput.C

- Fix refinement logic - wrap in a loop. Add a test
- Fix sparsity pattern for graph-partitioning based parallel simulations

Fix adaptive 3D multipatch simulations

---

src/SIM/AdaptiveSetup.C

Less chance of people not paying to details being confused.

added: print reason for stopping adaptive cycles

---

src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h

added: setCoord to ASMs3DLag

---

src/ASM/GlbL2projector.C
src/ASM/GlbL2projector.h
src/LinAlg/PETScMatrix.C
src/LinAlg/PETScMatrix.h

Allow using PETSc solvers with CGL2 version 2

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3Dmx.C
src/SIM/SIMoutput.C
src/Utility/AnaSol.C
src/Utility/Chebyshev.C
src/Utility/Chebyshev.h
src/Utility/Functions.C
src/Utility/Functions.h

This adds support for function based on Chebyshev interpolants.
Tests etc are missing, but let's review it first.

Add support for Chebyshev interpolant functions

---

Apps/Common/SIMSolver.h
src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs1DLag.C
src/ASM/ASMs1DLag.h
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DLag.h
src/ASM/ASMs2DTri.C
src/ASM/ASMs2DTri.h
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h

- Add the necessary write() methods so we can store lagrangian results in HDF5.
- Adjust check in the solver template

Add HDF5 output for lagrangian basis

---

src/SIM/AdaptiveSetup.C
src/SIM/AdaptiveSetup.h

t holds the adaptive step number. this allows for
flexible specification of how much to refine at each step.

added: allow specifying a function for beta

---

src/ASM/ASMs2D.C
src/ASM/ASMs3D.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu3D.C

empty myElms is not good enough - we might own 0 elements
on the patch

fixed: we need a separate bool to track if partitioning is enabled

---

src/IFEM.C
src/IFEM.h.in
src/SIM/SIMoptions.C
src/SIM/SIMoptions.h
src/Utility/DataExporter.C
src/Utility/DataExporter.h
src/Utility/HDF5Writer.C
src/Utility/HDF5Writer.h
src/Utility/LogStream.C
src/Utility/LogStream.h

Useful functionality i reckon.

added: ability to put terminal log in HDF5

---

src/Utility/DataExporter.h
src/Utility/HDF5Writer.C

Fix some small issues

---

src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3Dmx.C

Fix indexing issue in ASMu2Dmx. Add in ASMu3Dmx

Fix graph partitioning for mixed LR ASMs

---

Apps/Common/SIMSolver.h
Apps/Common/SIMSolverAdap.h
Apps/Common/SIMSolverTS.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMunstruct.h
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMLRSpline.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/SIM/SIMinput.C
src/SIM/SIMinput.h

Such that it also can be used on multi-patch models, for 3D, etc.
Most of this is more than 3 year old work, which found renewed usage now with the adaptive glass simulation case.

Support for general mesh density function on SIM level

---

src/ASM/ASMs2D.C
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DLag.h
src/ASM/ASMs3D.C
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h

add evaluate for ASMs3DLag

---

Apps/Common/SIMCoupled.h
Apps/Common/SIMCoupledSI.h
src/SIM/Property.h

Fixed: getMaxit() should always return 0 when staggering is disabled.
Added: Method to initialize parameters from an xml-tag.

Changed: Use ScalarFunc instead of RealFunc for max iterations.

---

src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/Test/TestASMu3D.C

Make the 2D and 3D implementations similar, for consistency.
Also (I believe) some minor bugs that have passed undetected so far.

ASMu3D::DirichletFace cleanup

---

src/ASM/ASMs2DLag.C
src/ASM/ASMs2DSpec.C
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DSpec.C

To avoid formatting mishaps in the future.

replace tabs with spaces

---

src/SIM/FunctionSum.C
src/SIM/FunctionSum.h

to give flexibility in subclasses

added: empty protected constructor in FunctionSum

---

src/ASM/IntegrandBase.h
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3Drecovery.C
src/SIM/NodeVecFunc.C
src/SIM/NodeVecFunc.h
src/SIM/SIMgeneric.C
src/SIM/SIMinput.C
src/Utility/Function.C
src/Utility/Function.h
src/Utility/Functions.C
src/Utility/Functions.h
src/Utility/Test/TestScopedLogger.C
src/Utility/Test/TestTractionField.C
src/Utility/TractionField.C
src/Utility/TractionField.h
src/Utility/Vec3.h

This adds a new class for specification of loads/in-homogeneous neumann conditions via a time-varying force resultant and direction, and a predefined explicit shape function defining the distribution over the loaded face.
Basic functionality needed by the DT Vind project.

Time-dependent surface traction fields

---

Apps/Common/scripts/iotest.sh.in
Apps/Common/scripts/regtest.sh.in
jenkins/build-ifem-module.sh

this to obtain a proper failed.log even if running multiple tests
in parallel

changed: make failed.log updates atomic in regression tests

---

3rdparty/expreval/func.cpp
3rdparty/expreval/node.h

In particular this quells a ton of cppcheck issues.

Some modernization in expreval

---

cmake/Modules/FindSuiteSparse.cmake
cmake/Scripts/IFEMTesting.cmake

changed: INT type is now INTERNAL

---

src/ASM/LR/ASMu3Dmx.C

meant projection was done on h/2 grid after adaptation.

fixed: forgotten condition in 3D subgrid with H mesh projection

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu3D.C

plus a bugfix for second derivatives in 3D.

Fix lagrange multipliers with single basis LR basis

---

src/SIM/SIMbase.C
src/SIM/SIMbase.h

Added: Debug print of nodal reaction forces.
Changed: Better property mapping outprint.

Added: Optional print of external load resultant.

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu3D.C

Add Integrand:::AVERAGE support to LR ASMs

---

Apps/Common/CompatibleOperators.C

I expect downstream failures..

fixed: wrong index in CompatibleOperators::Advection

---

Apps/Common/EqualOrderOperators.C

Example speedup for Chorin in 3D:
Semi-implicit (advectionoperator): From 22.5595 to 15.0467
Implicit (convectionoperator): From 123.926 to 50.3994

EqualOrderOperators: use outer_product in Advection and Convection

---

src/ASM/SplineFields3Dmx.C

fixed: wrong variable used in 3D mixed tensor spline fields

---

Apps/Common/SIMExplicitRK.h

This to aid prettifying in user code.

changed: suppress all output in RK solver if not standalone

---

src/ASM/ASMs2Dmx.C
src/ASM/ASMs3Dmx.C
src/ASM/GlbL2projector.C
src/ASM/GlbL2projector.h
src/ASM/Integrand.h
src/ASM/IntegrandBase.C
src/ASM/IntegrandBase.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3Dmx.C

And add necessary tracking of assembled status in BlockElmMats.

added: extend element matrix cache support to mixed

---

src/Utility/HDF5Writer.C

The *sol vector is considered the control point values of the
projected secondary solution if the description field equals "projected",
and the results field contains DataExporter::SECONDARY.

Fixed: HDF5-output of projected secondary solution

---

src/ASM/ReactionsOnly.C
src/ASM/ReactionsOnly.h
src/LinAlg/SAM.h
src/SIM/ForceIntegrator.C
src/SIM/ForceIntegrator.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/SIMgeneric.C
src/SIM/SIMgeneric.h

For calculation of interface forces between patches, instead of using the surface integral which is not that accurate

Added: Extract internal forces from ReactionsOnly integral

---

Apps/Common/CompatibleOperators.C
Apps/Common/EqualOrderOperators.C

- Skew-symmetric advection in EqualOrderOperators
- Conservative/skew-symmetric advection and convection in CompatibleOperators

Add more advection/convection forms

---

src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h

the problems leading to it being disabled should have been fixed now

re-enable multithreaded mixed 3D assembly

---

src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3Dmx.C

tensorspline was not cleared up after LR bases
had been established

fixed: memory leak in mixed LR integrands

---

src/ASM/GlbL2projector.C

necessary when using a fieldfunction

fixed: set parameters when projecting function

---

src/LinAlg/SAM.C

Fixup for commit 3ce4b7f36904303a01f0af1ef61ac5f5e402024a

---

src/ASM/DomainDecomposition.C
src/LinAlg/ISTLSolParams.C
src/LinAlg/PETScMatrix.C
src/LinAlg/PETScMatrix.h

Long been a TODO, finally got around to it.

Add support for block matrices with graph partitioned models

---

src/ASM/Integrand.h
src/SIM/SIMbase.C

this tells the integrand the index of the patch currently
being processed.

added: initPatch member in Integrand

---

src/ASM/LR/LRSplineField2D.C
src/ASM/LR/LRSplineField2D.h
src/ASM/LR/LRSplineField3D.C
src/ASM/LR/LRSplineField3D.h
src/ASM/SplineField2D.C
src/ASM/SplineField2D.h
src/ASM/SplineField3D.C
src/ASM/SplineField3D.h
src/Utility/FieldFunctions.C
src/Utility/FieldFunctions.h

- allow instancing Fields directly from surface/volumes
- allow instancing FieldFunctions for a pre-existing field

Some extensions for fields and field functions

---

src/ASM/ASMmxBase.C
src/ASM/ASMmxBase.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs3Dmx.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3Dmx.C

- fix wrong projection basis with tensor splines
- remove support for subgridH. this is not correct, we need to use two separate projection bases.

Some fixes for Subgrid

---

src/Utility/SplineUtils.C

Bad copy-paste syndrome here..

fixed: fix SplineUtils::project for 3D functions

---

src/ASM/DomainDecomposition.C
src/LinAlg/PETScMatrix.C

Also avoid some memory usage for unused arrays (G2LEQ for blocks).

added: proper preallocation for block matrices with graph partitioning

---

Apps/Common/Test/TestMultiPatchModelGenerator.C
Apps/Common/Test/TestSIMNodalConstraint.C
src/ASM/Test/TestASMs2D.C
src/ASM/Test/TestASMs3D.C
src/ASM/Test/TestASMsupel.C
src/Eig/Test/TestEigSolver.C
src/SIM/Test/TestModelGenerator.C
src/SIM/Test/TestSIM.C
src/Utility/Test/TestGaussQuadrature.C

use INSTANTIATE_TEST_SUITE_P instead of INSTANTIATE_TEST_CASE_P

---

Apps/CMakeLists.txt
cmake/Modules/FindTestLib.cmake

Ubuntu 22.04 warns some more. let's quell them.

Quell some cmake warnings

---

src/ASM/ASMs2D.C
src/ASM/ASMs3D.C
src/Utility/Test/TestUtilities.C
src/Utility/Utilities.C
src/Utility/Utilities.h

If we pass dirs=123 (the default) with less fields, stuff meets fan.

fixed: periodic single patch models with multiple bases

---

src/ASM/AlgEqSystem.h
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/Utility/Chebyshev.h
src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Function.h
src/Utility/Functions.C
src/Utility/Functions.h
src/Utility/Test/TestFunctions.C
src/Utility/TractionField.C
src/Utility/TractionField.h

Needed to support arclength control in nonlinear elasticity simulation with (pseudo)time-dependent loads or neumann conditions

Added: Time-derivative of time-dependent spatial functions

---

src/LinAlg/PETScMatrix.C
src/LinAlg/SAM.C
src/LinAlg/SAM.h

In particular this fixes graph partitioning with single patch periodic models.

Fix graphpartioning for models with MPCs

---

src/Utility/Functions.h

Flaw committed in f9370d3e67804f0205ae2421b4032840ff9c6459

Fixed: Potential infinite recursion

---

src/ASM/ASMs3DLag.C

Need this for the mpcci adapter.

added: set parameters in ASMs3DLag::integrate(B)

---

src/ASM/Test/TestASMs2D.C
src/ASM/Test/TestASMs3D.C
src/SIM/Test/TestNewmark.C

Fixed a valgrind issue in test problem (missing initialization)

---

src/ASM/LR/ASMu2D.C

fixed: use internal basis evaluation in jump integration method

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dnurbs.C

We need to duplicate this code from libLR since they evaluate the spline basis.

added: eps output functions for LR nurbs

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dnurbs.C
src/ASM/LR/LRSplineField.C
src/ASM/LR/LRSplineField.h
src/ASM/LR/LRSplineField2D.C
src/ASM/LR/LRSplineField2D.h
src/ASM/LR/LRSplineFields2D.C
src/ASM/LR/LRSplineFields2D.h
src/ASM/LR/LRSplineFields2Dmx.C

Add support for NURBS in LRSplineField(s)2D

---

cmake/Scripts/IFEMTesting.cmake

these tests were missing when using Apps/CMakeLists.txt

fixed: use correct path

---

src/ASM/ASMmxBase.C
src/ASM/LR/ASMu3Dmx.C

if not we risk getting the wrong setting if we instance a SIM with e.g. subgrid followed by instancing a SIM with Taylor-Hood.

fixed: make sure to always set geoBasis

---

src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMLRSpline.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h
src/ASM/LR/ASMu3Drecovery.C

ASMuxD: move projection and refinement bases into ASMLRSpline

---

src/ASM/ASMs2Dmx.C
src/ASM/ASMs3Dmx.C

and reuse getFirstItgElmNode while at it

rename some variables to make code more readable

---

src/ASM/LR/ASMu3D.C

use a lambda in ASMu3D::getBoundary1Nodes

---

src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Drecovery.C
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Drecovery.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Drecovery.C

To make code clearer and to kill temporarily introduced casts.

Use getBasis(xxx) in various spots

---

src/ASM/ASMmxBase.C
src/ASM/ASMmxBase.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2DmxLag.C
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3DmxLag.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/LRSplineFields2Dmx.C
src/ASM/LR/LRSplineFields3Dmx.C
src/ASM/SplineFields2Dmx.C
src/ASM/SplineFields3Dmx.C
src/LinAlg/Test/TestISTLMatrix.C
src/LinAlg/Test/TestPETScMatrix.C
src/LinAlg/Test/TestSAM.C
src/SIM/SIMbase.C
src/SIM/Test/TestSIM.C
src/Utility/Test/TestCoordinateMapping.C

More precise as this is the index of the integration basis.
Sits on top of https://github.com/OPM/IFEM/pull/615

Rename ASMmxBase::geoBasis to ASMmxBase::itgBasis

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3D.C

these ops intends to use the integration basis

ASMu2D(mx): use lrspline instead of geomB in various spots

---

Apps/Common/Test/TestCompatibleOperators.C
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2DmxLag.C
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3DmxLag.C
src/ASM/FiniteElement.C
src/ASM/FiniteElement.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3Dmx.C

Check for an additional entry at the end, and if so use this for the geometry basis.
Also adds Jacobian() for boundary use.

added: support for a separate geometry in MxFiniteElement::Jacobian/Hessian

---

src/ASM/ASMbase.h
src/ASM/ASMs1D.C
src/ASM/ASMs1D.h
src/ASM/ASMs1DLag.C
src/ASM/ASMs1DLag.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2DLag.C
src/ASM/ASMs2DLag.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Drecovery.C
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h
src/ASM/ASMsupel.C
src/ASM/ASMsupel.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/Test/TestASMs2Dmx.C

Ths enables a separate geometry in ASMs2Dmx.

ASMs2Dmx: add support for a separate geometry basis

---

src/ASM/ASMs2D.C
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMs3Dmx.C
src/ASM/ASMs3Dmx.h
src/ASM/ASMs3Drecovery.C
src/ASM/ASMstruct.C
src/ASM/ASMstruct.h
src/ASM/Test/TestASMs3Dmx.C
src/Utility/SplineUtils.C
src/Utility/SplineUtils.h

Same as https://github.com/OPM/IFEM/pull/623 but in 3D.
They have a common-ish commit (the forceItg param) so they are sort of dependent.

ASMs3Dmx: add support for a separate geometry basis

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Drecovery.C
src/ASM/LR/Test/TestASMu2Dmx.C

These are the changes required for 2DLR.

ASMu2Dmx: add support for a separate geometry basis

---

src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMLRSpline.h
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h
src/ASM/LR/ASMu3Drecovery.C
src/ASM/LR/Test/TestASMu3Dmx.C

Sits on top of https://github.com/OPM/IFEM/pull/626

ASMu3Dmx: add support for a separate geometry basis

---

src/ASM/LR/Test/ASMuSquare.h
src/ASM/LR/Test/TestLRSplineField.C
src/ASM/LR/Test/TestLRSplineFields.C
src/ASM/Test/TestSplineField.C
src/ASM/Test/TestSplineFields.C

While at it also plug some memory leaks.

changed: use ASM(mx)u(Cube|Square) in TestLRSplineField(s) 

---

src/ASM/ASMmxBase.C
src/ASM/ASMmxBase.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs3Dmx.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/Test/TestASMu2Dmx.C
src/ASM/LR/Test/TestASMu3Dmx.C
src/ASM/LR/Test/TestLRSplineFields.C
src/ASM/Test/TestASMs2Dmx.C
src/ASM/Test/TestASMs3Dmx.C
src/ASM/Test/TestSplineFields.C
src/Utility/SplineUtils.C
src/Utility/SplineUtils.h
src/Utility/Test/TestSplineUtils.C

does not make sense to use order raising since the geometry needs to be the highest order

changed: establishing RT basis now uses order lowering 

---

src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Functions.C

consistent with EvalFunction and more descriptive of what it does

changed: rename EvalFunc::derivative to EvalFunc::addDerivative

---

src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Test/TestFunctions.C

Consistent with spatial derivatives.

added: allow explicitly specifying time derivative of function

---

Apps/Common/EqualOrderOperators.C

also use MxV instead of loops in WeakOps::Divergence and ResidualOps::Divergence

EqualOrderOperators: cosmetics

---

Apps/Common/StabilizationUtils.C
Apps/Common/StabilizationUtils.h
Apps/Common/Test/TestStabilizationUtils.C

- Reformat code
- replace pointless bool return values with returns of the values calculated
- use norm2 and trace utility functions

StabilizationUtils: refactoring and cosmetics

---

src/LinAlg/matrix.h

I need these as well to tidy up some code in NavierStokes.

vector::add: also expose stridey and ofsy

---

src/Utility/ExprFunctions.C
src/Utility/Function.h
src/Utility/Test/TestFunctions.C

For the reasons described in https://github.com/OPM/IFEM/pull/639 this adds the same for the second derivatives.
Sits on top of https://github.com/OPM/IFEM/pull/639

RealFunc: add hessian() method

---

src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Function.h
src/Utility/TensorFunction.C
src/Utility/TensorFunction.h
src/Utility/Test/TestFunctions.C

returns the gradient of the function
Sits on top of https://github.com/OPM/IFEM/pull/638

added: (Tensor|Vec)Func::gradient

---

src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Function.h
src/Utility/TensorFunction.C
src/Utility/TensorFunction.h
src/Utility/Test/TestFunctions.C

returns the time derivative of the function
Sits on top of https://github.com/OPM/IFEM/pull/641

added: (Tensor|Vec)Func::timeDerivative 

---

src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Function.h
src/Utility/TensorFunction.C
src/Utility/TensorFunction.h
src/Utility/Test/TestFunctions.C

returns the second derivatives of the function
Sits on top of #642

added: (Tensor|Vec)Func::hessian 

---

Apps/Common/SIMSolver.h
src/ASM/ASMutils.C
src/ASM/BasisFunctionCache.h
src/ASM/LR/ASMu2D.C
src/Utility/Function.h
src/Utility/HDF5Restart.C

One compilation fix (missing <array> include) and various warning quells.

Clang warning and compilation fixes

---

Apps/Common/CompatibleOperators.C
Apps/Common/EqualOrderOperators.C
Apps/Common/EqualOrderOperators.h

and remove templating for the EqualOrder one

changed: optimize ResidualOperators::Laplacian

---

Apps/Common/EqualOrderOperators.C

changed: optimize various EqualOrderOperators

---

src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Test/TestFunctions.C

Sits on top of https://github.com/OPM/IFEM/pull/643

EvalFunc: add automatic differentiation support

---

src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Test/TestFunctions.C

Sits on top of https://github.com/OPM/IFEM/pull/647

EvalMultiFunction: add automatic differentiation support

---

src/SIM/SIMbase.C
src/Utility/AnaSol.C
src/Utility/AnaSol.h
src/Utility/ExprFunctions.C
src/Utility/ExprFunctions.h
src/Utility/Functions.C
src/Utility/Test/TestAnaSol.C

This allows deriving secondary solutions from the primary solution using AD or FD.
Sits on top of https://github.com/OPM/IFEM/pull/648

Analytic solutions: Allow derivation through AD or FD

---

src/ASM/ASMs2DLag.C
src/ASM/ASMs2DLag.h
src/ASM/ASMs2DTri.C
src/ASM/ASMs2DTri.h
src/ASM/ASMs3DLag.C
src/ASM/ASMs3DLag.h

Add adds support for projecting on the lagrangian space, not the spline space.

ASMsxDLag: add support for L2 projection

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2Dmx.h
src/ASM/ASMs3D.C
src/ASM/ASMs3D.h
src/ASM/ASMsupel.C
src/ASM/ASMsupel.h
src/ASM/BasisFunctionCache.C
src/ASM/BasisFunctionCache.h
src/ASM/Integrand.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/SIM/SIMgeneric.C
src/SIM/SIMoutput.C

This has now been tested and works within the expected limitations (in particular no boundary condition handling). Let's get it in before it gets lost in some dark git corner.

Add support for Piola mapping in 2D mixed ASMs

---

src/LinAlg/SAM.C
src/LinAlg/SAM.h
src/SIM/NewmarkSIM.C
src/SIM/NonLinSIM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/SIM/XMLInputBase.h
src/Utility/Utilities.h

To facilitate comparison with other nonlinear solvers.
Will probably not work for problems with rotational DOFs (beams), etc.

Added: Dump of total solution vector in equation order

---

src/ASM/ASMs2D.C
src/ASM/ASMs2D.h
src/ASM/ASMs2Dmx.C
src/ASM/ASMs2DmxLag.C
src/ASM/ASMu2DLag.C
src/ASM/ASMu2DLag.h
src/ASM/BasisFunctionCache.h

added: implement BasisFunctionCache for ASMu2DLag

---

Apps/Common/CompatibleOperators.C
Apps/Common/EqualOrderOperators.C

this was inconsistent with every other operator where the negation is implicit

ResidualOps: flip sign of Laplacian term

---

src/LinAlg/ISTLMatrix.C
src/LinAlg/ISTLMatrix.h
src/LinAlg/LinSolParams.C
src/LinAlg/PETScMatrix.C
src/LinAlg/PETScMatrix.h
src/LinAlg/PETScSolParams.h

Was not functional as we never parsed the setting in main context.

Fix preconditioner reset support

---

src/SIM/SIMoutput.C

If more than `nsd` components and a vector field name is provided as argument in SIMoutput::writeGlvS1(),
the scalar component names were duplicated. Also write exact vector field only if FE vector field is written.
With this fix the scalar component names will also be aligned with the names used on the HDF5 output,
which is an improvement by itself.
Don't dereference the myProblem pointer in writeGlvS() and writeGlvS1() without checking for null pointer first.

Fixed: Scalar component names on VTF

---

Apps/Common/CompatibleOperators.C
Apps/Common/PiolaOperators.C
Apps/Common/PiolaOperators.h

Similar to what we have have for equal order and div-compatible.

Add class for common Piola-mapped weak differential operators

---

Apps/Common/SIMSolverAdap.h
src/ASM/ASMunstruct.h
src/ASM/LR/ASMu2Dmx.C
src/SIM/AdaptiveSIM.C
src/SIM/AdaptiveSIM.h
src/Utility/FieldFunctions.C
src/Utility/FieldFunctions.h

This adds optional support for solution transfer in adaptive simulations. In particular add support for SIMSolverAdap using AdaptiveISolver.

AdaptiveSIM: support solution transfers

---

src/SIM/SIMoutput.C
src/SIM/SIMoutput.h

Relevant for structural beam and shell problems

Added: VTF output of boundary conditions on rotational DOFs (4-6)

---

src/LinAlg/SparseMatrix.C

A left-over from debugging the unstructured Nastran-file models.
The error condition ierr=ncol+1 is now accepted (but with a warning) instead of aborting the calculations.
Also some minor refactoring in here:
Moved error reporting outside the ifdef to avoid some duplication.
Let the `SuperLUdata` constructor allocate `perm_r` and `perm_c`.

Added: Accept near-singular matrices

---

src/SIM/SIMmodal.C
src/SIM/SIMmodal.h

Adding structural damping parameters, RHS and solution vectors as members in class SIMmodal.
Some of the virtual methods then no longer need to be virtual.

Modal simulation driver update

---

Apps/Common/CompatibleOperators.C
Apps/Common/PiolaOperators.C
src/Utility/FieldFunctions.C
src/Utility/FieldFunctions.h

In particular temperature block is now after the pressure block.
Add constructor to ScalarGradFieldFunction allowing construction from vector of field.

Adjust block indices for compatible operators

---

Apps/Common/EqualOrderOperators.C
Apps/Common/EqualOrderOperators.h

Split out from the Laplacian for reuse purposes

EqualOrderOperators: add Stress

---

Apps/Common/MultiPatchModelGenerator.C
Apps/Common/Test/TestMultiPatchModelGenerator.C
src/SIM/Property.h
src/SIM/SIMinput.C

- add support for conditions on multiple bases
- add support for analytic robin conditions
also extend the multipatch model generator to generate sets that is used with RT.

Extend support for analytic boundary conditions

---

src/ASM/ASMbase.h
src/ASM/ASMu1DLag.C
src/ASM/ASMu1DLag.h
src/ASM/ASMu2DLag.C
src/ASM/ASMu2DLag.h

Fixed: Wrong set referred in the non-const getElementSet() methods.
- continuation of the last commit of the now-merged #694

Added: virtual method ASMbase::isInElementSet().

---

src/LinAlg/SparseMatrix.C

fixed: build without superlu

---

src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Drecovery.C

Some small optimizations and cleanups in ASMu2D(recovery)

---

src/ASM/ASMs1D.C
src/ASM/FiniteElement.C
src/ASM/LR/ASMLRSpline.C
src/LinAlg/matrix.h
src/Utility/HDF5Writer.C
src/Utility/Legendre.C

Fixes for issues disclosed by debug-iterator builds.
Yes, will be squashed and commit messages pruned. Just for keeping track of things for now.

Fix issues disclosed by debug-iterator build

---

src/ASM/ASMbase.h
src/ASM/ASMu2DLag.C
src/ASM/ASMu2DLag.h
src/LinAlg/DenseMatrix.C
src/LinAlg/DenseMatrix.h
src/LinAlg/DiagMatrix.C
src/LinAlg/DiagMatrix.h
src/LinAlg/PETScMatrix.C
src/LinAlg/SPRMatrix.C
src/LinAlg/SPRMatrix.h
src/LinAlg/SparseMatrix.C
src/LinAlg/SparseMatrix.h
src/LinAlg/SystemMatrix.C
src/LinAlg/SystemMatrix.h
src/SIM/SIMinput.C

and some minor changes (mostly doxy) in System/SparseMatrix.

More element set methods in ASMu2DLag

---

Apps/Common/MultiPatchModelGenerator.C
Apps/Common/SIMExplicitRK.h
Apps/Common/Test/TestMultiPatchModelGenerator.C
src/ASM/ASMs2D.C
src/ASM/ASMs2DLag.C
src/ASM/ASMs3D.C
src/ASM/ASMs3Dmx.C
src/ASM/BasisFunctionVals.h
src/ASM/FiniteElement.h
src/ASM/IntegrandBase.h
src/ASM/LR/ASMu2D.C
src/LinAlg/matrix.h
src/SIM/SIMargsBase.h
src/Utility/BDF.h
src/Utility/ExprFunctions.h
src/Utility/Function.h
src/Utility/Functions.h
src/Utility/Tensor.h
src/Utility/Vec3.h

Avoid some copying and zero-initialize variables

Address some static analyzer issues

---

Apps/Common/CompatibleOperators.C
Apps/Common/PiolaOperators.C
Apps/Common/Test/TestCompatibleOperators.C

Upstream of https://github.com/sintefmath/IFEM-Stokes/pull/292

adjust indices in [Compatible|Piola] operators

---

src/Utility/Functions.C
src/Utility/Test/TestFunctions.C
src/Utility/Vec3.h

A convenience for doing, e.g., linear multi-loadcase simulation.

Added: Optional scaling parameter for Ramp, Dirac and Step functions

---

src/ASM/ASMs1D.C
src/ASM/ASMs1DLag.C
src/ASM/ASMsupel.C
src/LinAlg/MatVec.C
src/LinAlg/MatVec.h
src/LinAlg/Test/TestMatVec.C
src/SIM/SIMbase.C

Replaced by new implementations without the K index as argument. Including a unit test to verify the calculation.

Fixed: The congruence transformations were all wrong

---

cmake/Scripts/IFEMTesting.cmake
src/LinAlg/Test/MatrixTests.h
src/LinAlg/Test/NoBlas/TestMatrixFallback.C
src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h

and add tests for fallback (ie no blas) implementations
And fix issues disclosed by adding the tests

Extend matrix/vector tests

---

src/ASM/ASMs1DLag.C
src/ASM/ASMs2DLag.C
src/ASM/ASMs3DLag.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu3D.C

Changed: Check for element index out-of-range before using as array index.
This is a fixup for #735 which failed when exporting to VTF for models with Gls and Lagrange interpolation.

Fixed: Use nen=p1*p2(*p3) as loop range in case MNPC also contains GLMs.

---

Apps/Common/MultiPatchModelGenerator.C
Apps/Common/SIMMultiPatchModelGen.C
Apps/Common/SIMMultiPatchModelGen.h
Apps/Common/Test/MPI/TestMultiPatchModelGenerator.C
Apps/Common/Test/TestMultiPatchModelGenerator.C
src/ASM/LR/ASMLRSpline.C
src/ASM/LR/ASMLRSpline.h
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2D.h
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu2Dmx.h
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3D.h
src/ASM/LR/ASMu3Dmx.C
src/ASM/LR/ASMu3Dmx.h

This also provoked an almost 10 year old parsing bug for Poisson and an issue in ASMu2D.
The last commit is unrelated (cosmetic reorg. of some LR-methods).

Use standard single-patch generator unless specified otherwise

---

src/ASM/ASMbase.h
src/ASM/ASMs2DIB.C
src/ASM/ASMs2DIB.h
src/ASM/LR/ASMu2DIB.C
src/ASM/LR/ASMu2DIB.h
src/SIM/SIMoutput.C
src/Utility/ElementBlock.C
src/Utility/ElementBlock.h

Such that this method can be used for other kinds of additional geometries also (point masses, etc.)

Let the immersedGeometry() method define the name of the added geometry

---

src/ASM/AlgEqSystem.C
src/ASM/ReactionsOnly.C
src/LinAlg/PETScMatrix.C
src/LinAlg/PETScMatrix.h
src/LinAlg/PETScPCPerm.C
src/LinAlg/SystemMatrix.h
src/LinAlg/Test/MPI/TestISTLMatrix.C
src/LinAlg/Test/MPI/TestPETScMatrix.C
src/LinAlg/Test/TestISTLMatrix.C
src/LinAlg/Test/TestPETScMatrix.C

First part of #751. For the MPI testing (not able to run those locally...)

Some LinAlg updates

---

src/LinAlg/PETScMatrix.C
src/LinAlg/PETScMatrix.h
src/LinAlg/Test/TestPETScMatrix.C

Extracted from https://github.com/OPM/IFEM/pull/758

PETSc(Matrix|Vector): implement ::copy

---

src/ASM/ASMbase.C
src/ASM/ASMbase.h
src/ASM/ASMs2D.C
src/ASM/ASMs2DLag.C
src/ASM/ASMs2Dmx.C
src/ASM/ASMs3D.C
src/ASM/ASMs3DLag.C
src/ASM/ASMs3Dmx.C
src/ASM/LR/ASMu2D.C
src/ASM/LR/ASMu2Dmx.C
src/ASM/LR/ASMu3D.C
src/ASM/LR/ASMu3Dmx.C

Extending the partitioning support to more ASMs.

return early if process owns no elements on patch

---

src/ASM/DomainDecomposition.C
src/ASM/DomainDecomposition.h

instead of a SIM. for upcoming alternative use purposes

graphPartition: take element graph as parameter

---

src/ASM/GlbL2projector.C
src/SIM/SIMoptions.C

This adds support for partitioning L2 projection systems.

Add support for partitioning L2 projection systems

---

Apps/Common/CMakeLists.txt
cmake/Scripts/IFEMTesting.cmake

use cmake_parse_arguments. prettier, less error prone

changed: modernize ifem_add_test_app

---

src/LinAlg/Test/MatrixTests.h
src/LinAlg/Test/NoBlas/TestMatrixFallback.C
src/LinAlg/Test/TestMatrix.C

Add some sauce to the copy-pasta.

fixed: copy-paste error in TestVector.Norm / TestVectorFallback.Norm

---

src/LinAlg/Test/TestMatrix.C
src/LinAlg/matrix.h

Added: utl::vector::zero() and utl::matrix::zero()

---

src/ASM/ASMs1D.C
src/ASM/ASMu1DLag.C
src/ASM/ASMu2DLag.C
src/ASM/ElmMats.C
src/ASM/ElmMats.h
src/ASM/HHTMats.C
src/ASM/NewmarkMats.C
src/LinAlg/MatVec.C
src/LinAlg/MatVec.h
src/LinAlg/PETScMatrix.h
src/LinAlg/SAM.C
src/LinAlg/SAM.h
src/LinAlg/SystemMatrix.h
src/SIM/HHTSIM.C
src/SIM/NewmarkNLSIM.C
src/SIM/NewmarkSIM.C
src/SIM/SIMbase.C
src/SIM/SIMbase.h
src/Utility/Tensor.C
src/Utility/Tensor.h
src/Utility/Utilities.C
src/Utility/Utilities.h

Different smaller unrelated things (see commit log for details).

Various minor framework changed/additions to facilitate dynamics (Newmark) simulation
